// DIE TEXTE DES HAUPTFENSTERS -- alle, an einer Stelle.
//
// WARUM ES DIESE DATEI GIBT (03.09.). Die fuenf Nebenfenster hatten die
// Sprachschicht seit dem 11.08.; das Hauptfenster als einziges nicht. Jede
// seiner Beschriftungen stand fest im Quelltext, und weil die Chat-Ansicht
// darin ihre eigene, uebersetzte Tabelle mitbringt, standen im selben Fenster
// zwei Sprachen nebeneinander: die Seitenleiste deutsch, das Gespraech daneben
// englisch (.ui-review/chat-sitzung.png). Das ist kein Uebersetzungsfehler
// gewesen, sondern eine fehlende Schicht -- es gab keine Stelle, an der die
// Uebersetzung haette stehen koennen.
//
// DIESELBE BAUART wie in den Geschwistern (app/src/einstellungen/texte.ts und
// die vier anderen): eine Tabelle je Sprache, umgeschaltet ueber
// `setzeSprache()`, abgefragt ueber `t()`. shell/tests/test-app-sprache-paritaet.sh
// findet diese Datei von selbst und haelt fest, dass beide Tabellen dieselben
// Schluessel tragen -- sie muss dort nirgends eingetragen werden.
//
// ZWEI TABELLEN IM SELBEN FENSTER, und das ist Absicht: die Chat-Ansicht
// behaelt `chatbuehne/texte.ts`. Sie ist eine eigene Ansicht mit eigenem
// Wortschatz, sie wird an zwei Orten gezeigt (hier eingebettet und als eigenes
// Fenster), und ihre Tabelle einzuschmelzen haette den zweiten Ort kaputt
// gemacht. Beide bekommen dieselbe Sprache aus derselben Einstellung.
//
// DIE SCHLUESSEL folgen dem Schema der Geschwister:
//   leiste.<name>      die Symbolknoepfe links, mit `.tipp` fuer das Schildchen
//   panel.<name>.*     Titel, Platzhalter und Leermeldungen der vier Schubladen
//   worker.<name>      die Zustandswoerter auf den Worker-Kacheln
//   sitzung.<name>     was an einer Sitzungszeile steht
//   satz.<name>        ganze Saetze, die keinem Feld gehoeren
//   wort.<name>        einzelne Woerter der Bedienung
//   zeit.<name>        die Abstaende ("seit 3 Min.")
//
// PLATZHALTER stehen in geschweiften Klammern und bleiben stehen, wenn der Wert
// fehlt -- ein sichtbares `{name}` ist eine Meldung, ein stilles Loch ist keine.

/** Die Sprachen dieses Fensters. Beide tragen eine vollstaendige Tabelle. */
export type Sprache = 'de' | 'en';

/**
 * DEUTSCH. Referenztabelle: `alleSchluessel()` liest die Schluessel von hier,
 * und ein Schluessel, den EN nicht kennt, faellt auf den deutschen Text zurueck
 * statt zu verschwinden.
 */
export const DE: Record<string, string> = {
  'fenster.titel': 'Agent-Workbench',

  // --- Die Symbolknoepfe der linken Leiste ---------------------------------
  'leiste.ordner': 'Ordner',
  'leiste.ordner.tipp': 'Den Projektordner durchsehen und Dateien öffnen',
  'leiste.aktivitaet': 'Aktivität',
  'leiste.aktivitaet.tipp': 'Was die sichtbaren Sitzungen zuletzt geändert und abgeliefert haben',
  'leiste.freigaben': 'Freigaben',
  'leiste.freigaben.tipp': 'Angehaltene Worker, offene Anträge, der Verlauf des Guards',
  'leiste.protokolle': 'Protokolle',
  'leiste.protokolle.tipp': 'Die Protokolldateien dieser Maschine',
  'leiste.neu': 'Neue Sitzung',
  'leiste.neu.tipp': 'Eine Sitzung starten oder eine frühere fortsetzen',
  'leiste.einstellungen': 'Einstellungen',
  'leiste.einstellungen.tipp': 'Einstellungen öffnen',

  // --- Einzelne Woerter der Bedienung --------------------------------------
  'wort.schliessen': 'Schließen',

  // --- Umbenennen ----------------------------------------------------------
  'umbenennen.titel': 'Sitzung umbenennen',
  'umbenennen.ok': 'Umbenennen',
  'umbenennen.ab': 'Abbrechen',

  // --- Ordner --------------------------------------------------------------
  'panel.ordner.titel': 'Ordner',
  'panel.ordner.suche': 'Inhalt durchsuchen (rg) …',
  'panel.ordner.leer': 'Leer, oder alles hier ist ausgeschlossen.',
  'panel.ordner.ohneSuche': 'Die Suche steht nicht bereit: rg fehlt oder hat abgebrochen.',
  'panel.ordner.keinTreffer': 'Kein Treffer.',
  'panel.ordner.zeile': 'Zeile {zeile}',

  // --- Aktivität -----------------------------------------------------------
  'panel.aktivitaet.titel': 'Aktivität',
  'panel.aktivitaet.leer': 'Noch nichts für die sichtbaren Sitzungen.',
  'panel.aktivitaet.diff': 'Diff: {name}',
  'panel.aktivitaet.auftrag': 'Auftrag: {name}',
  'panel.aktivitaet.nochmal': '{pfad} – noch einmal klicken für {was}',
  'panel.aktivitaet.nochmal.diff': 'den Diff',
  'panel.aktivitaet.nochmal.auftrag': 'Auftrag und Ergebnis',

  // --- Protokolle ----------------------------------------------------------
  'panel.protokolle.titel': 'Protokolle',
  'panel.protokolle.fehlt': 'fehlt',
  'panel.protokolle.nochNicht': 'Diese Datei gibt es noch nicht: {pfad}',
  'panel.protokolle.oeffnen': '{pfad} öffnen',
  'panel.protokolle.tippFehlt': '{pfad} – gibt es noch nicht',

  // --- Freigaben -----------------------------------------------------------
  'panel.freigaben.titel': 'Freigaben',
  'panel.freigaben.blocks': 'Angehaltene Worker',
  'panel.freigaben.verlauf': 'Guard-Verlauf',
  'panel.freigaben.verlauf.hinweis':
    'Muster, die schon mehrmals angeschlagen haben, nach Häufigkeit zusammengefasst.',
  'panel.freigaben.antraege': 'Anträge',
  'panel.freigaben.keinBlock': 'Kein Worker wartet gerade auf eine Guard-Entscheidung.',
  'panel.freigaben.keinVerlauf': 'Noch keine Ablehnung aufgezeichnet.',
  'panel.freigaben.keinAntrag': 'Kein offener Antrag.',
  'panel.freigaben.paneZeigen': 'Pane zeigen',
  'panel.freigaben.grund': 'Begründung (freiwillig)',
  'panel.freigaben.grund.platzhalter': 'optional – ein Satz genügt',
  'panel.freigaben.einmalig':
    'Annehmen gilt für genau einen Durchlauf dieses Befehls und ist danach verbraucht. '
    + 'Der Worker führt ihn selbst noch einmal aus; hier startet nichts.',
  'panel.freigaben.antragHinweis':
    'Annehmen heißt: der Orchestrator startet diesen Worker von Hand. Es spawnt hier nichts von selbst.',
  'panel.freigaben.erteilt':
    'Freigabe erteilt – der Eintrag verschwindet, sobald sie gilt; der Worker wiederholt den Befehl selbst.',
  'panel.freigaben.abgelehnt': 'Abgelehnt – der Befehl bleibt angehalten.',
  'panel.freigaben.angenommenLaedt': 'Angenommen – wird neu geladen …',
  'panel.freigaben.abgelehntLaedt': 'Abgelehnt – wird neu geladen …',
  'panel.freigaben.ohneSitzung': 'Pane {pane} (keiner bekannten Sitzung zugeordnet)',
  'panel.freigaben.wartet': 'Wartet auf Freigabe · Muster: {muster}',
  'panel.freigaben.annehmen': 'Annehmen',
  'panel.freigaben.ablehnen': 'Ablehnen',

  // --- Die Sitzungsleiste links --------------------------------------------
  'sitzung.ohneTmux': 'keine tmux-Sitzung',
  'sitzung.verloren': 'lief noch, als dieses Fenster zuletzt hinsah',
  'sitzung.startet': 'startet gerade – bei einem lokalen Modell dauert das Minuten',
  'sitzung.startFehler': 'der Start ist gescheitert; der Grund stand in der Meldung',
  'sitzung.startetKurz': 'startet …',
  'sitzung.startetKurzFremd': 'startet … · {maschine}',
  'sitzung.startFehlerKurz': 'Start gescheitert',
  'sitzung.startFehlerKurzFremd': 'Start gescheitert · {maschine}',
  'sitzung.verlorenKurz': 'verloren · lief noch beim letzten Blick',
  'sitzung.workerZahl': '{n} Worker',
  'sitzung.workerZahlFremd': '{n} Worker · {maschine}',
  'sitzung.wiederherstellen': 'Sitzung wiederherstellen',
  'sitzung.wiederherstellen.frage': '„{name}“ auf {maschine} wiederbeleben?',
  'sitzung.wiederherstellen.ordner': 'Ordner',
  'sitzung.wiederherstellen.harness': 'Harness',
  'sitzung.wiederherstellen.jetzt': 'Wiederbeleben',
  'wort.abbrechen': 'Abbrechen',
  'sitzung.fortsetzen': 'Setzt die zuletzt gemerkte Unterhaltung fort ({id}).',
  'sitzung.neuStart': 'Startet neu – es war keine Unterhaltung gemerkt.',
  'umbenennen.bisher': 'Bisher: {name}',

  // --- Die Worker-Kacheln rechts -------------------------------------------
  'worker.kontext': '{prozent} % Kontext',
  'worker.kontextTokens': '{tokens}k Kontext',
  'worker.guard': 'angehalten vom Guard',
  'worker.entscheidung': 'wartet auf Entscheidung',
  'worker.haengt': 'hängt seit {dauer}',
  'worker.fertigMitErgebnis': 'fertig, Ergebnis da',
  'worker.fertigOhneErgebnis': 'fertig, kein Ergebnis',
  'worker.nichtEinsehbar': 'nicht einsehbar',
  'worker.aufAntrag': 'auf Antrag von {name}',
  'worker.anzahl': '{n} Worker',
  'worker.rubrikFertig': 'Fertig',
  'worker.rubrikNichtEinsehbar': 'Nicht einsehbar',
  'worker.rubrikUnbekannt': 'Unbekannt',
  'worker.laeuftSchlicht': 'läuft',
  'tab.marke': 'Tab {n}',

  // --- Die neue Oberflaeche (03.09.) ---------------------------------------
  // Titelleiste, Freigabeleiste, Baum, Tab-Leiste, Inspektor, Statusleiste.
  'leiste.projekte': 'Projekte',
  'modus.code': 'Code',
  'modus.code.tipp': 'Orchestrator und Worker in Terminal-Panes',
  'modus.agents': 'Agents',
  'modus.agents.tipp': 'Die Welten der Agents: Hauptagent, Teams, Kanal, Tickets und Skills',

  // --- Der Tab „Agents": Figurenvorschau und Fusszeile -------------------------
  // Vom Aufgaben-Blatt aus Fassung 26 (bis 14.09.2026) bleiben nur die Woerter,
  // die die Welten-Ansicht (Fusszeile, Knopf „Figuren") und figurenblatt.ts lesen.
  'agents.figuren': 'Figuren',
  'agents.figuren.tipp': 'Alle Rollen der Bibliothek in beiden Arten und alle Zustände',
  'agents.figuren.zurueck': 'Welt',
  'agents.fuss.keinStand': 'Kein Stand vom Kern',
  'agents.zustand.arbeitet': 'arbeitet',
  'agents.zustand.ergebnis_ungelesen': 'Ergebnis ungelesen',
  'agents.zustand.braucht_entscheidung': 'braucht Entscheidung',
  'agents.zustand.haengt': 'hängt',
  'agents.zustand.fertig': 'fertig',
  'agents.zustand.nicht_einsehbar': 'nicht einsehbar',
  'agents.rolle.teamleiter': 'Teamleiter',
  'agents.fuss.traegerSeit': 'Träger läuft seit {zeit}',
  'agents.fuss.traegerAus': 'Träger läuft nicht',
  'agents.fuss.aufgaben': '{n} Aufgaben',
  'agents.fuss.kernSauber': 'Kern sauber',
  'agents.fuss.kernUnsauber': 'Kern nicht sauber',
  'agents.fuss.kernUnbekannt': 'Kern sauber: unbekannt',
  'agents.fuss.lebenszeichenOk': 'Lebenszeichen {zeit} ok',
  'agents.fuss.lebenszeichenFehler': 'Lebenszeichen {zeit} fehlgeschlagen: {grund}',
  'agents.fuss.lebenszeichenNie': 'noch kein Lebenszeichen',
  'agents.fuss.verkehrOffen': 'Agent-Verkehr offen',
  'agents.fuss.verkehrPausiert': 'Agent-Verkehr pausiert',
  'agents.fuss.tageslimit': 'Tageslimit {verbraucht} von {erlaubt}',
  // Die Vorschau der Figuren (Abschnitt 7, „Das Aussehen der Agenten").
  'figuren.titel': 'Agentenfiguren',
  'figuren.einleitung': 'Jedes Team hat eine Farbe und eine Art. Die Art je Team steht in den Einstellungen unter agents.teams.<team>.art; ohne Eintrag gilt die Vorgabe.',
  'figuren.reduziert': 'Bewegung reduziert: jede Figur steht als Standbild.',
  'figuren.einzelne': 'Hauptagent und Reviewer',
  'figuren.kern': 'Hauptagent: der Kern',
  'figuren.linse': 'Reviewer: die Linse',
  'figuren.teams': 'Die Teams in beiden Arten',
  'figuren.art.roboter': 'Roboter',
  'figuren.art.tier': 'Tier',
  'figuren.vorgabe': 'Vorgabe {art}',
  'figuren.eingestellt': 'eingestellt {art}',
  'figuren.zustaende': 'Alle Zustände je Art',
  'figuren.ruhig': 'ruhig',
  'figuren.instanzen': 'Gleiche Rolle, nie dieselbe Figur',
  'figuren.groessen': 'Größen',
  'figuren.team.recherche': 'Recherche',
  'figuren.team.entwicklung': 'Entwicklung',
  'figuren.team.pruefung': 'Prüfung',
  'figuren.team.gestaltung': 'Gestaltung',
  // Der Platzhalter, solange das Feature nicht freigegeben ist (08.09.2026):
  // ein Satz, der sagt, was hier spaeter steht.
  'kopf.keineSitzung': 'Keine Sitzung gewählt',
  'sitzung.laeuft': 'läuft',
  'sitzung.wartet': 'wartet auf Dich',
  'sitzung.fern': 'nicht erreichbar',
  'sitzung.aus': 'aus',
  'baum.merkerWartet': 'In diesem Projekt wartet etwas auf Dich',
  'pane.orchestrator': 'Orchestrator',

  // DER LEERZUSTAND (03.09.2026, dritter Durchgang). Ohne Sitzung stand in der
  // Mitte eine schwarze Flaeche ohne ein Wort -- der erste Blick auf ein
  // frisches Programm sagte nichts darueber, was zu tun ist. Zwei Zeilen, weil
  // die Leiste links nicht auf sich selbst verweisen kann.
  'leer.buehne': 'Keine Sitzung. Lege mit + eine an oder wähle links ein Projekt.',
  'leer.baum': 'Noch keine Sitzung. Lege mit + eine an.',

  // --- Der Inhaltskopf und die Sitzungskarte (04.09.) ----------------------
  'flaeche.modus': 'Was die Fläche zeigt',
  'flaeche.orchestrator': 'Orchestrator',
  'flaeche.worker': 'Worker',
  'flaeche.workerLaufen': '{n} laufen',
  'flaeche.workerLaufen.tipp': 'Worker dieser Sitzung, die gerade arbeiten oder warten',
  'sitzungskarte.oeffnen': 'Diese Sitzung einstellen',
  'sitzungskarte.titel': 'Diese Sitzung',
  'sitzungskarte.name': 'Name',
  'sitzungskarte.uebernehmen': 'Übernehmen',
  'sitzungskarte.harness': 'Programm',
  'sitzungskarte.modell': 'Modell',
  'sitzungskarte.maschine': 'Maschine',
  'sitzungskarte.ordner': 'Ordner',
  'sitzungskarte.ordnerOeffnen': 'Ordner öffnen',

  'lage.uebersicht': 'Übersicht',
  'lage.uebersicht.tipp': 'Nur die Tabs und ihre Worker, ohne Terminalbild',
  'lage.gekachelt': 'Gekachelt',
  'lage.gekachelt.tipp': 'Alle Panes dieses Tabs nebeneinander',
  'lage.gezoomt': 'Gezoomt',
  'lage.gezoomt.tipp': 'Ein Pane auf der ganzen Fläche',
  'lage.ordnen': 'Ordnen',
  'lage.ordnen.tipp': 'Die Panes dieses Tabs gleichmäßig verteilen',
  'uebersicht.leer': 'In dieser Sitzung läuft gerade kein Worker.',

  'inspektor.schalter': 'Inspektor ein- und ausklappen',
  'inspektor.projekt': 'Projekt',
  'inspektor.orchestrator': 'Orchestrator',
  'inspektor.blattSchliessen': 'Dieses Blatt schließen',

  'freigabe.abzeichen': 'Offene Freigaben zeigen',
  'freigabe.wartetAufDich': 'wartet auf Dich',
  'freigabe.begruendung': 'Begründung',
  'freigabe.begruendungPlatzhalter': 'Begründung, falls Du eine hinterlassen willst …',
  'freigabe.begruendungHinweis': 'Freiwillig. Die Entscheidung geht sofort an den Worker zurück.',
  'freigabe.freigeben': 'Freigeben',
  'freigabe.ablehnen': 'Ablehnen',
  'freigabe.vorige': 'Vorige Freigabe',
  'freigabe.naechste': 'Nächste Freigabe',
  'freigabe.vonN': '{i} von {n}',
  'freigabe.hinspringen': 'Zu diesem Worker springen',
  'freigabe.antragUeber': 'Antrag auf einen Worker {name} mit {modell}',
  'freigabe.erteilt': 'Freigabe für {name} erteilt.',
  'freigabe.abgelehnt': 'Freigabe für {name} abgelehnt.',

  'status.workerLaufen': 'Worker laufen',
  'maschine.erreichbar': 'Erreichbar',
  'maschine.diese': 'diese Maschine',
  'maschine.unbekannt': 'nicht nachgesehen',
  'maschine.ja': 'ja',
  'maschine.nein': 'nein',
  'maschine.letzteAntwort': 'Letzte Antwort',
  'maschine.nieGeantwortet': 'noch nie geantwortet',
  'maschine.grund': 'Grund',
  'maschine.sitzungen': 'Sitzungen',
  'maschine.worker': 'Laufende Worker',
  'maschine.pruefstand': 'Prüfstand',
  'maschine.pausiert': 'pausiert',
  'maschine.erreichbarWort': 'erreichbar',
  'maschine.nichtErreichbarWort': 'nicht erreichbar',
  'maschine.kurz': '{sitzungen}\u00a0Sitzungen · {worker}\u00a0Worker',
  'maschine.hier': 'hier',
  'maschine.karte.tipp': 'Mehr zu dieser Maschine',
  'maschine.laden': 'Sitzungen laden',
  'maschine.ladenWirkung':
    'Ausgeschaltet wird diese Maschine nicht mehr über ssh abgefragt. Ihre Sitzungen laufen '
    + 'dort ungestört weiter; pausiert ist nur der Blick dieser Werkbank auf sie.',

  // --- Ganze Saetze ---------------------------------------------------------
  'satz.kachelung':
    '{proTab} Panes je Tab, gekachelt {spalten}x{zeilen} (Platz für bis zu {maxSpalten}x{maxZeilen})',
  'satz.kachelungKurz': '{proTab} Panes je Tab · {spalten}×{zeilen}',
  /* Die KURZE Fassung von satz.fremdeSitzung, fuer die sichtbare Zeile: sie
     sagt nur, dass nichts umgeräumt wird und warum. Das Ausfuehrliche steht
     daneben im Schildchen.
     ZWEI SCHLUESSEL statt einem, weil `t()` keine Mehrzahl kennt: mit einem
     einzigen stand dort "1 andere Clients hängen daran". */
  'satz.fremdeSitzungKurz.eins': 'nicht umgeräumt, ein anderer Client hängt daran',
  'satz.fremdeSitzungKurz': 'nicht umgeräumt, {n} andere Clients hängen daran',
  'satz.obergrenze': 'Obergrenze aus den Einstellungen greift',
  'satz.fremdeSitzung.eins':
    'Übernommene Sitzung, an der noch ein anderer Client hängt. Ihre Panes werden gezeichnet, aber '
    + 'nicht umgeräumt. Die Fenstergröße folgt trotzdem der Bühne und wird beim Ablösen zurückgestellt.',
  'satz.fremdeSitzung':
    'Übernommene Sitzung, an der noch {n} andere Clients hängen. Ihre Panes werden gezeichnet, aber '
    + 'nicht umgeräumt. Die Fenstergröße folgt trotzdem der Bühne und wird beim Ablösen zurückgestellt.',
  'satz.eigeneSitzung': 'Eigene Sitzung: die Bühne gibt ihr die Größe vor, sie ist ihr zugewiesen.',
  'satz.uebernommeneSitzung':
    'Übernommene Sitzung, an der sonst niemand hängt. Sie wird gekachelt und beim Ablösen zurückgestellt.',
  'satz.keinKanal':
    'Kein Steuerkanal: {grund} – das Fenster läuft weiter, Befehle von außen kommen nicht an.',

  // --- Der Editor in der Mitte ---------------------------------------------
  'editor.terminal': 'Terminal',
  'editor.senden': 'An Orchestrator senden',
  'editor.speichern': 'Datei speichern',
  'editor.ohneAuftragstext': '(kein aufgezeichneter Auftragstext)',
  'editor.ohneOrdner': 'Keine Sitzung gewählt – kein Projektordner',
  'editor.laedt': 'lädt: {name}',
  'editor.geoeffnet': 'geöffnet: {name}',
  'editor.gespeichert': 'gespeichert: {name}',
  'editor.speichernFehler': 'Speichern fehlgeschlagen: {grund}',
  'editor.sendenFehler': 'Senden fehlgeschlagen: {grund}',
  'editor.ohneDateiTab': 'Kein Datei-Tab gewählt',
  'editor.ohneAuswahl': 'Keine Auswahl markiert',
  'editor.ohneOrchestrator': 'Für diese Sitzung ist kein Orchestrator-Pane bekannt',
  'editor.gesendet': 'Auswahl an den Orchestrator geschickt',
  'editor.keinTreffer': 'kein Treffer',
  'editor.einklappen': 'Editor einklappen – die Panes bekommen den Platz zurück',
  'editor.aufklappen': 'Editor aufklappen',

  // --- Die uebernommenen Seiten im Rahmen ----------------------------------
  'seite.start': 'Startseite',
  'seite.rahmen': 'übernommene Seite',
  'seite.ausfuehren': 'Ausführen',
  'seite.ohneEmpfaenger': '„{befehl}“ hat hier noch keinen Empfänger.',
  'seite.nichtAusgefuehrt': '„{befehl}“ wird nicht ausgeführt.',

  // --- Meldungen ------------------------------------------------------------
  'meldung.ergebnisDa': 'Ergebnis da',
  'meldung.schliessen': 'Meldung schließen',
  'meldung.datei': 'Datei',
  'meldung.ergebnisUnter': '{name}: Ergebnis unter {pfad}',
  'meldung.ueberholt': 'überholt – dieser Auftrag ist nicht mehr der laufende',
  'meldung.ergebnisUeberholt':
    '{name}: Ergebnis unter {pfad} – überholt, der Worker hat inzwischen einen anderen Auftrag',

  // --- Fußzeile -------------------------------------------------------------
  'fuss.heute': '{tokens} heute',
  'fuss.budget': 'Budget – {text}',
  'fuss.budget.kurz': 'Budget: n. v.',
  'fuss.budget.fehlt': 'Budget: wb-budget nicht verfügbar',
  'fuss.pruefstand': 'Prüfstand {maschine}: {befunde}',
  'fuss.woche': 'Woche {prozent} %',
  'fuss.erlaubt': 'erlaubt {erlaubt} %',
  'fuss.woche.tipp': '{prozent} % des Wochenkontingents verbraucht; an einem gleichmäßig aufgeteilten Fenster wären bis heute Abend {erlaubt} % erlaubt.',

  // --- Zeitabstände ---------------------------------------------------------
  'zeit.geradeEben': 'gerade eben',
  'zeit.minuten': 'seit {n} Min.',
  'zeit.stunden': 'seit {n} Std.',
  'zeit.stundenMinuten': 'seit {std} Std. {min} Min.',
  'zeit.tage': 'seit {n} Tg.',

  // --- Welten-Ansicht (welten-view.ts, Auftrag agentsui Nr. 5) -------------
  'welten.stand.offen': 'offen',
  'welten.stand.laeuft': 'läuft',
  'welten.stand.wartet': 'wartet',
  'welten.stand.braucht_dich': 'braucht dich',
  'welten.stand.zur_abnahme': 'zur Abnahme',
  'welten.stand.abgenommen': 'abgenommen',
  'welten.stand.zurueckgegeben': 'zurückgegeben',
  'welten.stand.unterbrochen': 'unterbrochen',
  'welten.stand.verworfen': 'verworfen',
  'welten.stand.pausiert': 'pausiert',
  'welten.stand.gestoppt': 'gestoppt',
  'welten.zustand.braucht_dich': 'braucht dich',
  'welten.zustand.arbeitet': 'arbeitet',
  'welten.zustand.hat_ergebnis': 'hat Ergebnis',
  'welten.zustand.wartet': 'wartet',
  'welten.zustand.schlaeft': 'schläft',
  'welten.zustand.pausiert': 'pausiert',
  'welten.zustand.gestoppt': 'gestoppt',
  'welten.zustand.archiviert': 'archiviert',
  'welten.stufe.hauptagent': 'Hauptagent',
  'welten.stufe.teamleiter': 'Teamleiter',
  'welten.stufe.mitglied': 'Mitglied',
  'welten.stufe.leiterKurz': 'Leiter',
  'welten.frage.offen': 'offen',
  'welten.frage.beantwortet': 'beantwortet',
  'welten.frage.zurueckgenommen': 'zurückgenommen',
  'welten.vorschlag.offen': 'offen',
  'welten.vorschlag.uebernommen': 'übernommen',
  'welten.vorschlag.abgelehnt': 'abgelehnt',
  'welten.ereignis.erstellt': 'erstellt',
  'welten.ereignis.uebernommen': 'übernommen',
  'welten.ereignis.ergebnis': 'Ergebnis',
  'welten.ereignis.abgenommen': 'abgenommen',
  'welten.ereignis.zurueckgegeben': 'zurückgegeben',
  'welten.ereignis.unterbrochen': 'unterbrochen',
  'welten.ereignis.fortgesetzt': 'fortgesetzt',
  'welten.ereignis.zug': 'Zug',
  'welten.ereignis.rueckweg': 'Rückweg',
  'welten.ereignis.angelegt': 'angelegt',
  'welten.ereignis.profil': 'Profil geändert',
  'welten.ereignis.gedaechtnis': 'Gedächtnis geändert',
  'welten.ereignis.skill': 'Skill',
  'welten.ereignis.lernschritt': 'Lernschritt',
  'welten.ebene.agent': 'eigen',
  'welten.ebene.welt': 'Welt',
  'welten.ebene.bibliothek': 'Bibliothek',
  'welten.aktion.neu': 'angelegt',
  'welten.aktion.vorschlag': 'vorgeschlagen',
  'welten.aktion.abgenommen': 'übernommen',
  'welten.aktion.abgelehnt': 'abgelehnt',
  'welten.zug.gestopptWelt': 'gestoppt mit der Welt',
  'welten.zug.gestopptGrund': 'gestoppt: {a}',
  'welten.zug.eineFrage': 'braucht dich: eine Frage',
  'welten.zug.fragen': 'braucht dich: {a} Fragen',
  'welten.zug.ergebnisImChat': 'braucht dich: ein Ergebnis im Chat',
  'welten.zug.frageImChat': 'braucht dich: eine Frage im Chat',
  'welten.zug.brauchtBei': 'braucht dich bei {a}',
  'welten.zug.pausiertWelt': 'pausiert mit der Welt',
  'welten.zug.pausiertGrund': 'pausiert: {a}',
  'welten.zug.arbeitetAn': 'arbeitet an {a}',
  'welten.zug.ergebnisWartet': 'Ergebnis zu {a} wartet auf Abnahme',
  'welten.zug.wartetBei': 'wartet bei {a}',
  'welten.zug.schlaeftZurueck': 'schläft, {a} zurückgegeben',
  'welten.zug.schlaeftTickets': 'schläft, {a} Tickets offen',
  'welten.zug.schlaeftOffen': 'schläft, {a} offen',
  'welten.zug.schlaeftLaeuft': 'schläft, {a} läuft',
  // Auftrag agentaktiv: das Lebenszeichen am Avatar, der Stand unter der eigenen Nachricht, die Gründe des Trägers.
  'welten.leben.arbeitet': 'arbeitet',
  'welten.leben.arbeitetSeit': 'arbeitet seit {dauer}',
  'welten.leben.wartet': 'wartet auf den Träger',
  'welten.leben.weg': 'Träger nicht erreichbar',
  'welten.leben.schlaeft': 'schläft',
  'welten.antwort.zugestellt': 'zugestellt',
  'welten.antwort.geweckt': 'zugestellt · Träger geweckt',
  'welten.antwort.lief': 'zugestellt · Träger lief schon',
  'welten.antwort.nichtGeweckt': 'zugestellt · Träger nicht geweckt',
  'welten.antwort.arbeitet': '{name} arbeitet …',
  'welten.antwort.nichtGestartet': 'Träger hat den Zug nicht gestartet',
  'welten.antwort.nichtGestartetGrund': 'Träger hat den Zug nicht gestartet: {grund}',
  'welten.antwort.beendet': 'Zug endete ohne Antwort: {grund}',
  'welten.antwort.weg': 'zugestellt · Träger nicht erreichbar',
  'welten.grund.kontingent': 'Kontingent erschöpft',
  'welten.grund.anmeldung': 'Anmeldung fehlt',
  'welten.grund.recovery_limit': 'Wiederholungsgrenze erreicht',
  'welten.grund.pausiert': 'pausiert',
  'welten.grund.gestoppt': 'gestoppt',
  'welten.grund.ungeklaert': 'ungeklärter Lauf',
  'welten.grund.traeger_aus': 'Träger läuft nicht',
  'welten.grund.startfehler': 'Startfehler',
  'welten.grund.chain_limit': 'Kettengrenze erreicht',
  'welten.grund.cycle': 'Weckkreis erkannt',
  'welten.grund.nicht_erreichbar': 'nicht erreichbar',
  'welten.zugart.nachricht': 'Nachricht',
  'welten.zugart.ticket': 'Ticket',
  'welten.zugart.frage': 'Antwort auf eine Frage',
  'welten.zugart.recovery': 'Wiederaufnahme',
  'welten.lebenszeichen.titel': 'Zug',
  'welten.lebenszeichen.jetzt': 'Jetzt',
  'welten.lebenszeichen.art': 'Art',
  'welten.lebenszeichen.grund': 'Grund',
  'welten.lebenszeichen.wecker': 'Nächster Wecker',
  'welten.lebenszeichen.letzter': 'Letzter Zug',
  'welten.lebenszeichen.letzterText': '{zeit}, {ergebnis}',
  'welten.lebenszeichen.fehler': 'Lebenszeichen nicht lesbar: {text}',
  'welten.zeit.datum': '{tag}.{monat}. {uhr}',
  'welten.zeit.gerade': 'gerade',
  'welten.zeit.minuten': 'vor {n} min',
  'welten.zeit.stunden': 'vor {n} h',
  'welten.name.du': 'Du',
  'welten.name.steuerkanal': 'Steuerkanal',
  'welten.name.alle': 'alle',
  'welten.team': 'Team {name}',
  'welten.global': 'Global',
  'welten.zaehler.brauchtEins': '{n} braucht dich',
  'welten.zaehler.brauchenViele': '{n} brauchen dich',
  'welten.zaehler.laeuftEins': '{n} läuft',
  'welten.zaehler.laufenViele': '{n} laufen',
  'welten.zaehler.ticketEins': '{n} Ticket offen',
  'welten.zaehler.ticketsViele': '{n} Tickets offen',
  'welten.messung.zugEins': '{n} Zug',
  'welten.messung.zuegeViele': '{n} Züge',
  'welten.messung.mittel': 'Mittel {wert}',
  'welten.messung.letzte': 'letzte {n}: {wert} ({werte})',
  'welten.meldung.keinKern': 'Keine Verbindung zum Kern.',
  'welten.meldung.rueckgabeOhneBemerkung': 'Die Rückgabe braucht eine Bemerkung, was fehlt.',
  'welten.meldung.ablehnungOhneGrund': 'Die Ablehnung braucht einen Grund.',
  'welten.meldung.ausblenden': 'Ausblenden',
  'welten.adresse.fehlt': 'Im Kanal braucht die Nachricht mindestens eine Adresse.',
  'welten.adresse.unbekannt': '„@{name}“ ist weder Agent noch Team in {welt}.',
  'welten.adresse.alleAllein': '„@alle“ steht allein.',
  'welten.leiste.vorlagen': 'Vorlagen:',
  'welten.leiste.baum': 'Baum',
  'welten.leiste.liste': 'Liste',
  'welten.leiste.inkonsistent': 'Stand während eines Schreibvorgangs gelesen',
  'welten.leiste.teams': 'Teams',
  'welten.leiste.aktiv': '{n} aktiv',
  'welten.leiste.ohneTeam': 'Ohne Team',
  'welten.leiste.agenten': 'Agenten',
  'welten.kopf.globaleWelt': 'Globale Welt',
  'welten.kopf.inspektor': 'Inspektor',
  'welten.kanal.name': 'Kanal',
  'welten.kanal.nachrichtEins': '{n} Nachricht',
  'welten.kanal.nachrichtenViele': '{n} Nachrichten',
  'welten.kanal.unter': 'Alle Agenten von {welt} · {n} Nachrichten · nur Adressierte werden geweckt',
  'welten.reiter.chat': 'Chat',
  'welten.reiter.tickets': 'Tickets',
  'welten.chat.mitDir': 'Mit dir',
  'welten.chat.direktMit': 'Direkt mit {namen}',
  'welten.chat.leer': 'Noch kein Gespräch',
  'welten.chat.leerAgent': 'Du kannst {name} schreiben. Antworten und Berichte erscheinen hier; Fragen gehen den Dienstweg über Teamleiter und Hauptagent.',
  'welten.chat.leerKanal': 'Im Kanal schreiben alle Agenten der Welt, adressiert.',
  'welten.chat.direktNurLesen': 'Direktchat zwischen Agenten, nur zum Lesen.',
  'welten.chat.an': 'An',
  'welten.chat.nachrichtAn': 'Nachricht an {name}',
  'welten.chat.nachrichtKanal': 'Nachricht in den Kanal',
  'welten.chat.senden': 'Senden',
  'welten.nachricht.an': 'an {namen}',
  'welten.nachricht.frageAnDich': 'Frage an dich',
  'welten.nachricht.ergebnisFuerDich': 'Ergebnis für dich',
  'welten.nachricht.ticket': 'Ticket „{titel}“',
  'welten.nachricht.quittieren': 'Zur Kenntnis genommen',
  'welten.nachricht.quittiert': 'zur Kenntnis genommen',
  'welten.frage.band': 'Eine offene Frage von {name}: „{text}“',
  'welten.frage.ansehen': 'Ansehen',
  'welten.frage.kopf': 'Frage von {name} · {stand}',
  'welten.frage.empfohlen': '{option} (empfohlen)',
  'welten.frage.eigeneAntwort': 'Eigene Antwort',
  'welten.frage.antworten': 'Antworten',
  'welten.frage.zuruecknehmen': 'Zurücknehmen …',
  'welten.frage.antwortVon': 'Antwort von {name}: {text}',
  'welten.tickets.filterOffen': 'Offen',
  'welten.tickets.filterAlle': 'Alle',
  'welten.tickets.neu': 'Neues Ticket',
  'welten.tickets.neuIn': 'Neues Ticket in {welt}',
  'welten.tickets.titel': 'Titel',
  'welten.tickets.ziel': 'Ziel',
  'welten.tickets.fertig': 'Fertig heißt',
  'welten.tickets.hauptagentEntscheidet': 'Hauptagent entscheidet',
  'welten.tickets.keine': 'Keine Tickets in dieser Auswahl.',
  'welten.tickets.alle': '‹ Alle Tickets',
  'welten.ticket.an': 'an {namen}',
  'welten.ticket.von': 'von {name}',
  'welten.ticket.wartetAuf': 'wartet auf {liste}',
  'welten.detail.auftrag': 'Auftrag',
  'welten.detail.adressiertAn': 'Adressiert an',
  'welten.detail.bearbeiter': 'Bearbeiter',
  'welten.detail.absender': 'Absender',
  'welten.detail.angelegt': 'Angelegt',
  'welten.detail.ergebnis': 'Ergebnis',
  'welten.detail.zurueckgegeben': 'Zurückgegeben',
  'welten.detail.abnahme': 'Abnahme',
  'welten.detail.wasFehlt': 'Was fehlt, in einem Satz',
  'welten.detail.zurueckgeben': 'Zurückgeben',
  'welten.detail.zurueckgebenOffen': 'Zurückgeben …',
  'welten.detail.verlauf': 'Verlauf',
  'welten.vorschlag.titel': 'Skill-Vorschlag',
  'welten.vorschlag.zeile': '„{skill}“ von {agent} für {ziel} · prüft {pruefer} · {stand}',
  'welten.vorschlag.zielBibliothek': 'die Bibliothek',
  'welten.vorschlag.zielWelt': 'die Welt',
  'welten.vorschlag.begruendung': 'Begründung: {text}',
  'welten.vorschlag.version': 'Stand {version}, Zielebene bisher {basis}',
  'welten.vorschlag.neu': 'neu',
  'welten.vorschlag.diffGekuerzt': '[… gekürzt; vollständig in diff.txt]',
  'welten.vorschlag.uebernommenVon': 'Übernommen von {name}',
  'welten.vorschlag.abgelehntVon': 'Abgelehnt von {name}',
  'welten.vorschlag.grundPlatzhalter': 'Warum nicht, in einem Satz',
  'welten.vorschlag.ablehnen': 'Ablehnen',
  'welten.vorschlag.ablehnenOffen': 'Ablehnen …',
  'welten.vorschlag.uebernehmen': 'Übernehmen',
  'welten.vorschlag.pruefen': 'Prüfen: keine Agentenregel gelockert, keine Freigabe umgangen, kein doppelter Zweck.',
  'welten.knopf.abbrechen': 'Abbrechen',
  'welten.knopf.anlegen': 'Anlegen',
  'welten.knopf.pruefen': 'Prüfen',
  'welten.knopf.sichern': 'Sichern',
  'welten.knopf.verwerfen': 'Verwerfen',
  'welten.knopf.bearbeiten': 'Bearbeiten',
  'welten.knopf.bearbeitenOffen': 'Bearbeiten …',
  'welten.wort.keiner': 'keiner',
  'welten.wort.keine': 'keine',
  'welten.wort.leer': 'leer',
  'welten.wort.keineEingetragen': 'keine eingetragen',
  'welten.feld.spezialgebiet': 'Spezialgebiet',
  'welten.feld.modell': 'Modell',
  'welten.feld.denkstufe': 'Denkstufe',
  'welten.feld.fallback': 'Fallback',
  'welten.feld.fallbackDenkstufe': 'Fallback-Denkstufe',
  'welten.feld.maschine': 'Maschine',
  'welten.feld.werkzeuge': 'Werkzeuge',
  'welten.feld.bash': 'Bash-Muster',
  'welten.feld.kontextgrenze': 'Kontextgrenze',
  'welten.welt.titel': 'Welt',
  'welten.welt.art': 'Art',
  'welten.welt.projekt': 'Projekt',
  'welten.welt.ablage': 'Ablage',
  'welten.welt.stand': 'Stand',
  'welten.welt.agentenTeamEins': '{n} in {m} Team',
  'welten.welt.agentenTeamsViele': '{n} in {m} Teams',
  'welten.welt.ticketsOffen': '{n}, davon {m} offen',
  'welten.welt.fragen': 'Fragen',
  'welten.welt.fragenOffen': '{n} offen von {m}',
  'welten.welt.sofortstopp': 'Sofortstopp',
  'welten.welt.sofortstoppText': 'Sperrt neue Starts und beendet laufende Züge der ganzen Welt. Tickets in Arbeit werden unterbrochen, nie als Erfolg gezählt.',
  'welten.welt.stoppen': 'Welt sofort stoppen …',
  'welten.antrag.titel': 'Anträge an den Hauptagenten',
  'welten.antrag.zeile': '{agent} für Team {team} · {stand} – von {name}: {text}',
  'welten.antrag.offen': 'offen',
  'welten.antrag.angelegt': 'angelegt',
  'welten.antrag.abgelehnt': 'abgelehnt',
  'welten.antrag.entscheidet': 'Entscheiden kann nur {name} (wb-agent antrag-entscheiden).',
  'welten.antrag.derHauptagent': 'der Hauptagent',
  'welten.blatt.profil': 'Profil',
  'welten.blatt.protokoll': 'Protokoll',
  'welten.blatt.gedaechtnis': 'Gedächtnis',
  'welten.blatt.skills': 'Skills',
  'welten.protokoll.hinweis': 'Das Zugprotokoll mit Werkzeugaufrufen liefert erst der Träger. Bis dahin steht hier, was {name} in Tickets eingetragen hat und was am Profil oder Gedächtnis geändert wurde.',
  'welten.protokoll.ticketEintrag': '{ereignis} „{titel}“',
  'welten.gedaechtnis.bearbeiten': 'Gedächtnis bearbeiten',
  'welten.gedaechtnis.warnung': 'Das Gedächtnis pflegt {name} selbst. Deine Fassung ersetzt MEMORY.md; wurde die Datei inzwischen geändert, wird nichts gesichert, und du lädst neu.',
  'welten.profil.betrieb': 'Betrieb',
  'welten.profil.schalter': 'Schalter',
  'welten.profil.stoppen': 'Sofort stoppen …',
  'welten.profil.postfach': 'Postfach: {n} von {m} noch nicht quittiert',
  'welten.profil.bearbeiten': 'Profil bearbeiten',
  'welten.profil.modellBeispiel': 'z. B. sonnet5:high',
  'welten.profil.fallbackLeer': 'leer = keiner',
  'welten.profil.modellwechsel': 'Ein Modellwechsel gilt ab dem nächsten Start; ein laufender Zug behält sein Modell.',
  'welten.profil.angelegtVon': 'von {name}',
  'welten.profil.vorlage': 'Vorlage {name}',
  'welten.profil.kennung': 'Kennung',
  'welten.skills.keine': 'Noch keine Skills. Wiederkehrende Arbeit wird beim zweiten Mal Skript, beim dritten Mal Skill.',
  'welten.skills.zuklappen': 'SKILL.md zuklappen',
  'welten.skills.zeigen': 'SKILL.md zeigen',
  'welten.skills.vorgeladen': 'vorgeladen',
  'welten.skills.verdeckt': 'verdeckt: {liste}',
  'welten.skills.gleicherStand': '(gleicher Stand)',
  'welten.skills.veraltet': 'skills.json ist älter als der Ordner.',
  'welten.skills.gekuerzt': '[… gekürzt]',
  'welten.skills.fehlt': 'Fehlt: {liste} (im Profil vorgeladen, auf keiner Ebene vorhanden)',
  'welten.skills.ungueltig': 'Ungültig: {liste}',
  'welten.skills.quelleStand': 'Aus skills.json, Stand {zeit}.',
  'welten.skills.quelle': 'Aus skills.json.',
  'welten.skills.quelleOrdner': 'Ohne skills.json aus den Skillordnern aufgelöst.',
  'welten.skills.token': 'Token je Ticketart',
  'welten.skills.keineMessung': 'Noch keine Messung. Der Träger schreibt je Zug eine Zeile nach messungen.jsonl.',
  'welten.skills.verlauf': 'Skill-Verlauf',
  'welten.skills.nochNichts': 'Noch nichts.',
  'welten.anlegen.titel': 'Agent anlegen',
  'welten.anlegen.in': 'Agent anlegen in {welt}',
  'welten.anlegen.weltSteht': 'Die Welt ist {stand}; angelegt wird erst, wenn sie läuft.',
  'welten.anlegen.unter': 'in {welt} · gültig erst mit „Anlegen“, gestartet wird dabei nichts',
  'welten.anlegen.ausVorlage': 'Aus der Vorlage „{titel}“.',
  'welten.anlegen.beschreibungFehlt': 'Beschreibe zuerst in eigenen Worten, was der Agent tun soll.',
  'welten.anlegen.vorschlagVon': 'Vorschlag von {kennung}, Denkstufe {stufe}{kosten}.',
  'welten.anlegen.vorschlagLaeuft': 'Vorschlag läuft …',
  'welten.anlegen.vorschlagErzeugen': 'Vorschlag erzeugen',
  'welten.anlegen.beschreibung': 'Beschreibung',
  'welten.anlegen.beschreibungFuss': 'Nur die Beschreibung genügt: das Modell entwirft den Rest, kopflos, ohne Werkzeuge und ohne Zugriff auf die Welt. Was du selbst gesetzt hast, bleibt.',
  'welten.anlegen.beschreibungPlatzhalter': 'Was soll der Agent tun? In eigenen Worten',
  'welten.anlegen.vorlage': 'Vorlage',
  'welten.anlegen.ohneTeam': 'ohne Team',
  'welten.anlegen.neuesTeamOffen': 'Neues Team …',
  'welten.anlegen.agent': 'Agent',
  'welten.anlegen.name': 'Name',
  'welten.anlegen.stufe': 'Stufe',
  'welten.anlegen.team': 'Team',
  'welten.anlegen.neuesTeam': 'Neues Team',
  'welten.anlegen.neuesTeamPlatzhalter': 'Name des neuen Teams',
  'welten.anlegen.einSatz': 'in einem Satz',
  'welten.anlegen.modellUndMaschine': 'Modell und Maschine',
  'welten.anlegen.modellFuss': 'Aus wb-state models table, Fable nie. Lokal, wo es reicht; der Mac nur, wenn die Arbeit dort sein muss.',
  'welten.anlegen.werkzeugeUndGrenzen': 'Werkzeuge und Grenzen',
  'welten.anlegen.werkzeugeFuss': 'Gesperrt bleibt, was die Hausliste sperrt: Push, rm -rf, kill, Mail-Versand, Erlaubnisstufen.',
  'welten.anlegen.einsJeZeile': 'eins je Zeile',
  'welten.anlegen.kommaGetrennt': 'durch Komma getrennt',
  'welten.anlegen.kontextPlatzhalter': 'was der Agent nicht erfährt',
  'welten.anlegen.figur': 'Figur',
  'welten.anlegen.hauptagentKern': 'Der Hauptagent trägt den Kern.',
  'welten.anlegen.farbe': 'Farbe',
  'welten.anlegen.anweisungen': 'Anweisungsdatei (AGENTS.md)',
  'welten.anlegen.anweisungenFuss': 'Leer lassen: die Datei entsteht beim Anlegen aus der Hausvorlage mit Rolle, Spezialgebiet, Grenzen und Meldewegen.',
  'welten.anlegen.hausvorlage': 'Aus der Hausvorlage erzeugen',
  'welten.figur.roboter': 'Roboter',
  'welten.figur.tier': 'Tier',
  'welten.figur.linse': 'Linse',
  'welten.farbe.entwicklung': 'Entwicklung',
  'welten.farbe.recherche': 'Recherche',
  'welten.farbe.pruefung': 'Prüfung',
  'welten.farbe.gestaltung': 'Gestaltung',
  'welten.vorschau.titel': 'Vorschau',
  'welten.vorschau.ohneNamen': 'ohne Namen',
  'welten.vorschau.anweisungen': 'Anweisungsdatei',
  'welten.vorschau.ausHausvorlage': 'Entsteht beim Anlegen aus der Hausvorlage.',
  'welten.dialog.hinweis': 'Das geschieht über die Datenbibliothek der Welt und steht danach in ihren Dateien.',
  'welten.dialog.stoppen': 'Stoppen',
  'welten.dialog.zuruecknehmen': 'Zurücknehmen',
  'welten.leer.laden': 'Die Welten werden geladen',
  'welten.leer.ladenText': 'Der Kern liest die Welten über die Datenbibliothek.',
  'welten.leer.keineWelt': 'Noch keine Welt',
  'welten.leer.keineWeltText': 'Agents arbeiten in Welten: Ein Hauptagent nimmt deine Aufträge an, Teams verteilen sie unter sich. Eine Welt gehört zu einem Projektordner oder gilt global und hat ihren eigenen Kanal, ihre Tickets und ihr Gedächtnis.',
  'welten.leer.danach': 'Danach: den Hauptagenten anlegen, selbst oder als Vorschlag, dann das Team aufbauen und Aufträge im Chat oder als Ticket geben. Auf der Kommandozeile geht dasselbe mit „wb-welt neu <projekt>/.werkbank/agents“.',
  'welten.neu.knopf': 'Neue Welt …',
  'welten.neu.projekt': 'Projektwelt',
  'welten.neu.projektText': 'Die Agenten arbeiten in einem Projektordner; die Welt liegt dort unter .werkbank/agents.',
  'welten.neu.ordner': 'Projektordner',
  'welten.neu.ordnerPlatzhalter': 'Absoluter Pfad des Projektordners',
  'welten.neu.ordnerFehlt': 'Trage zuerst den Projektordner ein.',
  'welten.neu.anlegen': 'Welt anlegen',
  'welten.neu.global': 'Globale Welt',
  'welten.neu.globalText': 'Für Aufgaben über alle Projekte, ohne Ordner. Sie liegt unter {pfad}.',
  'welten.neu.globalAnlegen': 'Globale Welt anlegen',
  'welten.neu.globalDa': 'Die globale Welt gibt es schon.',
  'welten.neu.maschine': 'Maschine',
  'welten.neu.maschineHier': 'Die Welt entsteht hier und bekommt ihren Träger.',
  'welten.neu.maschineMac': 'Die Welt entsteht auf dem Mac. Hier läuft kein Träger, Agenten antworten hier nicht.',
  'welten.neu.maschineOhneTraeger': 'Die Welt entsteht auf {maschine}. Dort läuft kein Träger, Agenten antworten dort nicht.',
  'welten.neu.maschineFern': 'Die Welt entsteht auf {maschine} unter demselben Pfad relativ zum Benutzerordner und bekommt dort ihren Träger.',
  'welten.neu.maschineWeg': '{maschine} ist nicht erreichbar ({text}). Angelegt wird erst, wenn {maschine} antwortet.',
  'welten.neu.maschineFrage': '{maschine} ist noch nicht gefragt; ob es erreichbar ist, zeigt sich spätestens beim Anlegen.',
  'welten.maschine.titel': 'Maschine',
  'welten.maschine.diese': '{maschine}, diese',
  'welten.maschine.verbindung': 'Verbindung',
  'welten.maschine.erreichbar': 'erreichbar',
  'welten.maschine.wegSeit': 'nicht erreichbar seit {zeit}: {text}',
  'welten.maschine.traeger': 'Träger',
  'welten.maschine.traegerLaeuft': 'eingerichtet, läuft',
  'welten.maschine.traegerSchlaeft': 'eingerichtet, schläft',
  'welten.maschine.traegerEingerichtet': 'eingerichtet',
  'welten.maschine.traegerFehlt': 'nicht eingerichtet',
  'welten.maschine.traegerUnmoeglich': 'auf dieser Maschine nicht möglich',
  'welten.zugaenge.titel': 'Zugänge',
  'welten.zugaenge.zeile': '{liste} – eingerichtet vom Menschen, gilt für alle Agenten der Welt',
  'welten.maschine.umziehen': 'Nach {maschine} umziehen …',
  'welten.maschine.umziehenText': 'Die Ablage zieht unter demselben Pfad auf die Maschine; hier bleibt sie als …umgezogen-<Datum> liegen, nichts wird gelöscht. Vorher prüft die Werkbank beide Seiten und fragt zurück.',
  'welten.maschine.hinweisWeg': '{maschine} nicht erreichbar seit {zeit}. Zu sehen ist der letzte Stand; Handlungen gehen wieder, sobald {maschine} antwortet.',
  'welten.maschine.hinweisMac': 'Auf dem Mac läuft kein Träger, Agenten antworten hier nicht.',
  'welten.maschine.hinweisOhneTraeger': 'Auf {maschine} läuft kein Träger, Agenten antworten hier nicht.',
  'welten.maschine.hinweisNichtEingerichtet': 'Auf {maschine} ist für diese Welt kein Träger eingerichtet; Agenten antworten erst, wenn er eingerichtet ist.',
  'welten.maschine.fussErreichbar': '{maschine} erreichbar, {n} Träger',
  'welten.maschine.fussWeg': '{maschine} nicht erreichbar seit {zeit}',
  'welten.dialog.umziehen': 'Umziehen',
  'welten.anlegen.hauptagent': 'Hauptagent anlegen',
  'welten.anlegen.hauptagentOffen': 'Hauptagent anlegen …',
  'welten.anlegen.vorschlagen': 'Vorschlagen lassen …',
  'welten.anlegen.grundFehler': 'Die Welt ist nicht vollständig lesbar; angelegt wird erst, wenn sie es wieder ist.',
  'welten.anlegen.vorschlagHinweis': 'Beschreibe in ein, zwei Sätzen, was der neue Agent in {welt} verantworten soll; „Vorschlag erzeugen“ füllt den Rest.',
  'welten.anlegen.vorschlagHinweisHaupt': 'Beschreibe in ein, zwei Sätzen, wofür {welt} da ist und was der Hauptagent verantworten soll; „Vorschlag erzeugen“ füllt den Rest.',
  'welten.anlegen.gespraech': 'Gespräch',
  'welten.anlegen.formular': 'Formular',
  'welten.anlegen.ansichtTipp': 'Den Entwurf im Gespräch mit einem Modell ausmachen oder im Formular selbst setzen; beide zeigen denselben Entwurf.',
  'welten.anlegen.gespraechTitel': 'Im Gespräch entwerfen',
  'welten.anlegen.gespraechEinladung': 'Beschreibe in eigenen Worten, was der neue Agent in {welt} tun soll: Zweck, Ton, Aufgaben, Grenzen.',
  'welten.anlegen.gespraechEinladungHaupt': 'Beschreibe in eigenen Worten, wofür {welt} da ist und was der Hauptagent verantworten soll: Zweck, Ton, Aufgaben, Grenzen.',
  'welten.anlegen.gespraechErklaerung': 'Das Modell fragt nach, schlägt Werte vor und trägt sie in den Entwurf ein; die Vorschau rechts zeigt den Stand. Im Formular lässt sich jederzeit alles ändern, und was du dort selbst setzt, bleibt. Das Modell arbeitet kopflos, ohne Werkzeuge und ohne Zugriff auf die Welt.',
  'welten.anlegen.gespraechPlatzhalter': 'Was soll der Agent tun?',
  'welten.anlegen.gespraechAntwortPlatzhalter': 'Antwort an das Modell',
  'welten.anlegen.gespraechModell': 'Modell für das Gespräch',
  'welten.anlegen.gespraechLaeuft': '{modell} antwortet …',
  'welten.anlegen.gespraechFertig': 'Aus Sicht des Modells vollständig. Prüfen, dann anlegen.',
  'welten.anlegen.sendenTipp': 'Senden (⌘↩)',
  'welten.anlegen.nachrichtFehlt': 'Schreib zuerst, was der Agent tun soll.',
  'welten.anlegen.antwortVon': 'Antwort von {kennung}, Denkstufe {stufe}{kosten}.',
  'welten.anlegen.zuletztGesetzt': 'Zuletzt gesetzt: {felder}',
  'welten.anlegen.gesetzt': 'Gesetzt: {felder}',
  'welten.anlegen.imFormular': 'Im Formular ansehen',
  'welten.anlegen.du': 'Du',
  'welten.anlegen.modell': 'Modell',
  'welten.entwurfsfeld.id': 'Name',
  'welten.entwurfsfeld.stage': 'Stufe',
  'welten.entwurfsfeld.team': 'Team',
  'welten.entwurfsfeld.specialty': 'Spezialgebiet',
  'welten.entwurfsfeld.model': 'Modell',
  'welten.entwurfsfeld.effort': 'Denkstufe',
  'welten.entwurfsfeld.fallback_model': 'Fallback',
  'welten.entwurfsfeld.fallback_effort': 'Fallback-Denkstufe',
  'welten.entwurfsfeld.machine': 'Maschine',
  'welten.entwurfsfeld.tools': 'Werkzeuge',
  'welten.entwurfsfeld.bash': 'Bash-Muster',
  'welten.entwurfsfeld.skills': 'Skills',
  'welten.entwurfsfeld.context_limit': 'Kontextgrenze',
  'welten.entwurfsfeld.figure': 'Figur',
  'welten.entwurfsfeld.instructions': 'Anweisungsdatei',
  'welten.entwurfsfeld.template': 'Vorlage',
  'welten.einladung.titel': 'Diese Welt hat noch keinen Hauptagenten.',
  'welten.einladung.text': 'Lege ihn an oder lass ihn vorschlagen. Er nimmt deine Aufträge an, verteilt sie als Tickets an die Teams und fragt dich nur, wenn es nicht anders geht.',
  'welten.leiste.hauptagent': 'Hauptagent',
  'welten.leiste.keinHauptagent': 'Noch kein Hauptagent',
};

/**
 * ENGLISCH, die Auslieferungssprache. Vollstaendig gepflegt: jeder Schluessel
 * aus DE steht auch hier, und keiner mehr -- die Suite haelt das fest.
 */
export const EN: Record<string, string> = {
  'fenster.titel': 'Agent Workbench',

  'leiste.ordner': 'Files',
  'leiste.ordner.tipp': 'Browse the project folder and open files',
  'leiste.aktivitaet': 'Activity',
  'leiste.aktivitaet.tipp': 'What the visible sessions changed and delivered most recently',
  'leiste.freigaben': 'Approvals',
  'leiste.freigaben.tipp': 'Held workers, open requests, and the guard history',
  'leiste.protokolle': 'Logs',
  'leiste.protokolle.tipp': 'The log files on this machine',
  'leiste.neu': 'New session',
  'leiste.neu.tipp': 'Start a session, or resume an earlier one',
  'leiste.einstellungen': 'Settings',
  'leiste.einstellungen.tipp': 'Open settings',

  'wort.schliessen': 'Close',

  'umbenennen.titel': 'Rename session',
  'umbenennen.ok': 'Rename',
  'umbenennen.ab': 'Cancel',

  'panel.ordner.titel': 'Files',
  'panel.ordner.suche': 'Search contents (rg) …',
  'panel.ordner.leer': 'Empty, or everything here is excluded.',
  'panel.ordner.ohneSuche': 'Search is unavailable: rg is missing or gave up.',
  'panel.ordner.keinTreffer': 'No match.',
  'panel.ordner.zeile': 'Line {zeile}',

  'panel.aktivitaet.titel': 'Activity',
  'panel.aktivitaet.leer': 'Nothing yet for the visible sessions.',
  'panel.aktivitaet.diff': 'Diff: {name}',
  'panel.aktivitaet.auftrag': 'Task: {name}',
  'panel.aktivitaet.nochmal': '{pfad} — click again for {was}',
  'panel.aktivitaet.nochmal.diff': 'the diff',
  'panel.aktivitaet.nochmal.auftrag': 'task and result',

  'panel.protokolle.titel': 'Logs',
  'panel.protokolle.fehlt': 'missing',
  'panel.protokolle.nochNicht': 'This file does not exist yet: {pfad}',
  'panel.protokolle.oeffnen': 'Open {pfad}',
  'panel.protokolle.tippFehlt': '{pfad} — does not exist yet',

  'panel.freigaben.titel': 'Approvals',
  'panel.freigaben.blocks': 'Held workers',
  'panel.freigaben.verlauf': 'Guard history',
  'panel.freigaben.verlauf.hinweis':
    'Patterns that have tripped more than once, collected by how often.',
  'panel.freigaben.antraege': 'Requests',
  'panel.freigaben.keinBlock': 'No worker is waiting on a guard decision.',
  'panel.freigaben.keinVerlauf': 'No refusal recorded yet.',
  'panel.freigaben.keinAntrag': 'No open request.',
  'panel.freigaben.paneZeigen': 'Show pane',
  'panel.freigaben.grund': 'Reason (optional)',
  'panel.freigaben.grund.platzhalter': 'optional — one sentence is enough',
  'panel.freigaben.einmalig':
    'Approving covers exactly one run of this command and is spent afterwards. '
    + 'The worker runs it again itself; nothing starts from here.',
  'panel.freigaben.antragHinweis':
    'Approving means the orchestrator starts this worker by hand. Nothing spawns here on its own.',
  'panel.freigaben.erteilt':
    'Approved — the entry disappears once it takes effect; the worker repeats the command itself.',
  'panel.freigaben.abgelehnt': 'Refused — the command stays held.',
  'panel.freigaben.angenommenLaedt': 'Approved — reloading …',
  'panel.freigaben.abgelehntLaedt': 'Refused — reloading …',
  'panel.freigaben.ohneSitzung': 'Pane {pane} (not matched to any known session)',
  'panel.freigaben.wartet': 'Waiting for approval · pattern: {muster}',
  'panel.freigaben.annehmen': 'Approve',
  'panel.freigaben.ablehnen': 'Refuse',

  'sitzung.ohneTmux': 'no tmux session',
  'sitzung.verloren': 'was still running when this window last looked',
  'sitzung.startet': 'starting up — with a local model this takes minutes',
  'sitzung.startFehler': 'the start failed; the reason was in the notice',
  'sitzung.startetKurz': 'starting …',
  'sitzung.startetKurzFremd': 'starting … · {maschine}',
  'sitzung.startFehlerKurz': 'start failed',
  'sitzung.startFehlerKurzFremd': 'start failed · {maschine}',
  'sitzung.verlorenKurz': 'lost · still running when last seen',
  'sitzung.workerZahl': '{n} workers',
  'sitzung.workerZahlFremd': '{n} workers · {maschine}',
  'sitzung.wiederherstellen': 'Restore session',
  'sitzung.wiederherstellen.frage': 'Revive “{name}” on {maschine}?',
  'sitzung.wiederherstellen.ordner': 'Folder',
  'sitzung.wiederherstellen.harness': 'Harness',
  'sitzung.wiederherstellen.jetzt': 'Revive',
  'wort.abbrechen': 'Cancel',
  'sitzung.fortsetzen': 'Resumes the conversation last remembered ({id}).',
  'sitzung.neuStart': 'Starts fresh — no conversation was remembered.',
  'umbenennen.bisher': 'Currently: {name}',

  'worker.kontext': '{prozent} % context',
  'worker.kontextTokens': '{tokens}k context',
  'worker.guard': 'held by the guard',
  'worker.entscheidung': 'waiting for a decision',
  'worker.haengt': 'stalled for {dauer}',
  'worker.fertigMitErgebnis': 'done, result is in',
  'worker.fertigOhneErgebnis': 'done, no result',
  'worker.nichtEinsehbar': 'cannot be inspected',
  'worker.aufAntrag': 'requested by {name}',
  'worker.anzahl': '{n} workers',
  'worker.rubrikFertig': 'Done',
  'worker.rubrikNichtEinsehbar': 'Cannot be inspected',
  'worker.rubrikUnbekannt': 'Unknown',
  'worker.laeuftSchlicht': 'running',
  'tab.marke': 'Tab {n}',

  'leiste.projekte': 'Projects',
  'modus.code': 'Code',
  'modus.code.tipp': 'Orchestrator and workers in terminal panes',
  'modus.agents': 'Agents',
  'modus.agents.tipp': 'The agents worlds: main agent, teams, channel, tickets and skills',

  'agents.figuren': 'Figures',
  'agents.figuren.tipp': 'Every role of the library in both kinds and every state',
  'agents.figuren.zurueck': 'World',
  'agents.fuss.keinStand': 'No state from the core',
  'agents.zustand.arbeitet': 'working',
  'agents.zustand.ergebnis_ungelesen': 'result unread',
  'agents.zustand.braucht_entscheidung': 'needs a decision',
  'agents.zustand.haengt': 'stalled',
  'agents.zustand.fertig': 'done',
  'agents.zustand.nicht_einsehbar': 'not visible',
  'agents.rolle.teamleiter': 'Team lead',
  'agents.fuss.traegerSeit': 'Carrier running since {zeit}',
  'agents.fuss.traegerAus': 'Carrier not running',
  'agents.fuss.aufgaben': '{n} tasks',
  'agents.fuss.kernSauber': 'Core clean',
  'agents.fuss.kernUnsauber': 'Core not clean',
  'agents.fuss.kernUnbekannt': 'Core clean: unknown',
  'agents.fuss.lebenszeichenOk': 'Health check {zeit} ok',
  'agents.fuss.lebenszeichenFehler': 'Health check {zeit} failed: {grund}',
  'agents.fuss.lebenszeichenNie': 'no health check yet',
  'agents.fuss.verkehrOffen': 'Agent traffic open',
  'agents.fuss.verkehrPausiert': 'Agent traffic paused',
  'agents.fuss.tageslimit': 'Daily limit {verbraucht} of {erlaubt}',
  'figuren.titel': 'Agent figures',
  'figuren.einleitung': 'Every team has a colour and a kind. The kind per team lives in the settings under agents.teams.<team>.art; without an entry the default applies.',
  'figuren.reduziert': 'Reduced motion: every figure is a still image.',
  'figuren.einzelne': 'Lead agent and reviewer',
  'figuren.kern': 'Lead agent: the core',
  'figuren.linse': 'Reviewer: the lens',
  'figuren.teams': 'The teams in both kinds',
  'figuren.art.roboter': 'Robot',
  'figuren.art.tier': 'Creature',
  'figuren.vorgabe': 'default {art}',
  'figuren.eingestellt': 'set to {art}',
  'figuren.zustaende': 'Every state per kind',
  'figuren.ruhig': 'idle',
  'figuren.instanzen': 'Same role, never the same figure',
  'figuren.groessen': 'Sizes',
  'figuren.team.recherche': 'Research',
  'figuren.team.entwicklung': 'Development',
  'figuren.team.pruefung': 'Review',
  'figuren.team.gestaltung': 'Design',
  'kopf.keineSitzung': 'No session selected',
  'sitzung.laeuft': 'running',
  'sitzung.wartet': 'waiting for you',
  'sitzung.fern': 'unreachable',
  'sitzung.aus': 'stopped',
  'baum.merkerWartet': 'Something in this project is waiting for you',
  'pane.orchestrator': 'Orchestrator',

  'leer.buehne': 'No session. Create one with + or pick a project on the left.',
  'leer.baum': 'No sessions yet. Create one with +.',

  // --- Der Inhaltskopf und die Sitzungskarte (04.09.) ----------------------
  'flaeche.modus': 'What the surface shows',
  'flaeche.orchestrator': 'Orchestrator',
  'flaeche.worker': 'Workers',
  'flaeche.workerLaufen': '{n} working',
  'flaeche.workerLaufen.tipp': 'Workers of this session that are running or waiting',
  'sitzungskarte.oeffnen': 'Settings for this session',
  'sitzungskarte.titel': 'This session',
  'sitzungskarte.name': 'Name',
  'sitzungskarte.uebernehmen': 'Apply',
  'sitzungskarte.harness': 'Program',
  'sitzungskarte.modell': 'Model',
  'sitzungskarte.maschine': 'Machine',
  'sitzungskarte.ordner': 'Folder',
  'sitzungskarte.ordnerOeffnen': 'Open folder',

  'lage.uebersicht': 'Overview',
  'lage.uebersicht.tipp': 'Just the tabs and their workers, without terminal output',
  'lage.gekachelt': 'Tiled',
  'lage.gekachelt.tipp': 'All panes of this tab side by side',
  'lage.gezoomt': 'Zoomed',
  'lage.gezoomt.tipp': 'One pane filling the stage',
  'lage.ordnen': 'Tidy',
  'lage.ordnen.tipp': 'Spread the panes of this tab evenly',
  'uebersicht.leer': 'No worker is running in this session.',

  'inspektor.schalter': 'Show or hide the inspector',
  'inspektor.projekt': 'Project',
  'inspektor.orchestrator': 'Orchestrator',
  'inspektor.blattSchliessen': 'Close this panel',

  'freigabe.abzeichen': 'Show open approvals',
  'freigabe.wartetAufDich': 'is waiting for you',
  'freigabe.begruendung': 'Reason',
  'freigabe.begruendungPlatzhalter': 'A reason, if you want to leave one …',
  'freigabe.begruendungHinweis': 'Optional. The decision goes straight back to the worker.',
  'freigabe.freigeben': 'Approve',
  'freigabe.ablehnen': 'Reject',
  'freigabe.vorige': 'Previous approval',
  'freigabe.naechste': 'Next approval',
  'freigabe.vonN': '{i} of {n}',
  'freigabe.hinspringen': 'Jump to this worker',
  'freigabe.antragUeber': 'Request for a worker {name} on {modell}',
  'freigabe.erteilt': 'Approved for {name}.',
  'freigabe.abgelehnt': 'Rejected for {name}.',

  'status.workerLaufen': 'workers running',
  'maschine.erreichbar': 'Reachable',
  'maschine.diese': 'this machine',
  'maschine.unbekannt': 'not checked',
  'maschine.ja': 'yes',
  'maschine.nein': 'no',
  'maschine.letzteAntwort': 'Last answer',
  'maschine.nieGeantwortet': 'never answered',
  'maschine.grund': 'Reason',
  'maschine.sitzungen': 'Sessions',
  'maschine.worker': 'Running workers',
  'maschine.pruefstand': 'Check status',
  'maschine.pausiert': 'paused',
  'maschine.erreichbarWort': 'reachable',
  'maschine.nichtErreichbarWort': 'unreachable',
  'maschine.kurz': '{sitzungen}\u00a0sessions · {worker}\u00a0workers',
  'maschine.hier': 'here',
  'maschine.karte.tipp': 'More about this machine',
  'maschine.laden': 'Load sessions',
  'maschine.ladenWirkung':
    'Switched off, this machine is no longer polled over ssh. Its sessions keep running there '
    + 'undisturbed; what is paused is only this workbench looking at them.',

  'satz.kachelung':
    '{proTab} panes per tab, tiled {spalten}x{zeilen} (room for up to {maxSpalten}x{maxZeilen})',
  'satz.kachelungKurz': '{proTab} panes per tab · {spalten}×{zeilen}',
  'satz.fremdeSitzungKurz.eins': 'not rearranged, another client is attached',
  'satz.fremdeSitzungKurz': 'not rearranged, {n} other clients are attached',
  'satz.obergrenze': 'the cap from the settings applies',
  'satz.fremdeSitzung.eins':
    'Adopted session with one other client still attached. Its panes are drawn but not rearranged. '
    + 'The window size follows the stage regardless, and is restored on detaching.',
  'satz.fremdeSitzung':
    'Adopted session with {n} other clients still attached. Its panes are drawn but not rearranged. '
    + 'The window size follows the stage regardless, and is restored on detaching.',
  'satz.eigeneSitzung': 'Own session: the stage sets its size, and that size is assigned to it.',
  'satz.uebernommeneSitzung':
    'Adopted session with nobody else attached. It is tiled, and restored on detaching.',
  'satz.keinKanal':
    'No control channel: {grund} — the window keeps running, commands from outside will not arrive.',

  'editor.terminal': 'Terminal',
  'editor.senden': 'Send to orchestrator',
  'editor.speichern': 'Save file',
  'editor.ohneAuftragstext': '(no task text was recorded)',
  'editor.ohneOrdner': 'No session selected — no project folder',
  'editor.laedt': 'loading: {name}',
  'editor.geoeffnet': 'opened: {name}',
  'editor.gespeichert': 'saved: {name}',
  'editor.speichernFehler': 'Saving failed: {grund}',
  'editor.sendenFehler': 'Sending failed: {grund}',
  'editor.ohneDateiTab': 'No file tab selected',
  'editor.ohneAuswahl': 'Nothing selected',
  'editor.ohneOrchestrator': 'No orchestrator pane is known for this session',
  'editor.gesendet': 'Selection sent to the orchestrator',
  'editor.keinTreffer': 'no match',
  'editor.einklappen': 'Collapse editor — the panes get the space back',
  'editor.aufklappen': 'Expand editor',

  'seite.start': 'Home',
  'seite.rahmen': 'adopted page',
  'seite.ausfuehren': 'Run',
  'seite.ohneEmpfaenger': '“{befehl}” has no receiver here yet.',
  'seite.nichtAusgefuehrt': '“{befehl}” will not be run.',

  'meldung.ergebnisDa': 'Result is in',
  'meldung.schliessen': 'Dismiss',
  'meldung.datei': 'File',
  'meldung.ergebnisUnter': '{name}: result at {pfad}',
  'meldung.ueberholt': 'superseded — this is no longer the task being worked on',
  'meldung.ergebnisUeberholt':
    '{name}: result at {pfad} — superseded, the worker has since moved to another task',

  'fuss.heute': '{tokens} today',
  'fuss.budget': 'Budget — {text}',
  'fuss.budget.kurz': 'Budget: n/a',
  'fuss.budget.fehlt': 'Budget: wb-budget unavailable',
  'fuss.pruefstand': 'Test bench {maschine}: {befunde}',
  'fuss.woche': 'Week {prozent} %',
  'fuss.erlaubt': 'allowed {erlaubt} %',
  'fuss.woche.tipp': '{prozent} % of the weekly allowance is used; spread evenly across the window, {erlaubt} % would be allowed by tonight.',

  'zeit.geradeEben': 'just now',
  'zeit.minuten': '{n} min ago',
  'zeit.stunden': '{n} h ago',
  'zeit.stundenMinuten': '{std} h {min} min ago',
  'zeit.tage': '{n} d ago',

  // --- Welten-Ansicht (welten-view.ts, Auftrag agentsui Nr. 5) -------------
  'welten.stand.offen': 'open',
  'welten.stand.laeuft': 'running',
  'welten.stand.wartet': 'waiting',
  'welten.stand.braucht_dich': 'needs you',
  'welten.stand.zur_abnahme': 'awaiting approval',
  'welten.stand.abgenommen': 'approved',
  'welten.stand.zurueckgegeben': 'returned',
  'welten.stand.unterbrochen': 'interrupted',
  'welten.stand.verworfen': 'discarded',
  'welten.stand.pausiert': 'paused',
  'welten.stand.gestoppt': 'stopped',
  'welten.zustand.braucht_dich': 'needs you',
  'welten.zustand.arbeitet': 'working',
  'welten.zustand.hat_ergebnis': 'has a result',
  'welten.zustand.wartet': 'waiting',
  'welten.zustand.schlaeft': 'asleep',
  'welten.zustand.pausiert': 'paused',
  'welten.zustand.gestoppt': 'stopped',
  'welten.zustand.archiviert': 'archived',
  'welten.stufe.hauptagent': 'Main agent',
  'welten.stufe.teamleiter': 'Team lead',
  'welten.stufe.mitglied': 'Member',
  'welten.stufe.leiterKurz': 'Lead',
  'welten.frage.offen': 'open',
  'welten.frage.beantwortet': 'answered',
  'welten.frage.zurueckgenommen': 'withdrawn',
  'welten.vorschlag.offen': 'open',
  'welten.vorschlag.uebernommen': 'accepted',
  'welten.vorschlag.abgelehnt': 'rejected',
  'welten.ereignis.erstellt': 'created',
  'welten.ereignis.uebernommen': 'claimed',
  'welten.ereignis.ergebnis': 'result',
  'welten.ereignis.abgenommen': 'approved',
  'welten.ereignis.zurueckgegeben': 'returned',
  'welten.ereignis.unterbrochen': 'interrupted',
  'welten.ereignis.fortgesetzt': 'resumed',
  'welten.ereignis.zug': 'turn',
  'welten.ereignis.rueckweg': 'return path',
  'welten.ereignis.angelegt': 'created',
  'welten.ereignis.profil': 'profile changed',
  'welten.ereignis.gedaechtnis': 'memory changed',
  'welten.ereignis.skill': 'skill',
  'welten.ereignis.lernschritt': 'learning step',
  'welten.ebene.agent': 'own',
  'welten.ebene.welt': 'World',
  'welten.ebene.bibliothek': 'Library',
  'welten.aktion.neu': 'created',
  'welten.aktion.vorschlag': 'proposed',
  'welten.aktion.abgenommen': 'accepted',
  'welten.aktion.abgelehnt': 'rejected',
  'welten.zug.gestopptWelt': 'stopped with the world',
  'welten.zug.gestopptGrund': 'stopped: {a}',
  'welten.zug.eineFrage': 'needs you: one question',
  'welten.zug.fragen': 'needs you: {a} questions',
  'welten.zug.ergebnisImChat': 'needs you: a result in the chat',
  'welten.zug.frageImChat': 'needs you: a question in the chat',
  'welten.zug.brauchtBei': 'needs you on {a}',
  'welten.zug.pausiertWelt': 'paused with the world',
  'welten.zug.pausiertGrund': 'paused: {a}',
  'welten.zug.arbeitetAn': 'working on {a}',
  'welten.zug.ergebnisWartet': 'result for {a} awaits approval',
  'welten.zug.wartetBei': 'waiting on {a}',
  'welten.zug.schlaeftZurueck': 'asleep, {a} returned',
  'welten.zug.schlaeftTickets': 'asleep, {a} tickets open',
  'welten.zug.schlaeftOffen': 'asleep, {a} open',
  'welten.zug.schlaeftLaeuft': 'asleep, {a} in progress',
  'welten.leben.arbeitet': 'working',
  'welten.leben.arbeitetSeit': 'working for {dauer}',
  'welten.leben.wartet': 'waiting for the carrier',
  'welten.leben.weg': 'carrier unreachable',
  'welten.leben.schlaeft': 'asleep',
  'welten.antwort.zugestellt': 'delivered',
  'welten.antwort.geweckt': 'delivered · carrier woken',
  'welten.antwort.lief': 'delivered · carrier was already running',
  'welten.antwort.nichtGeweckt': 'delivered · carrier not woken',
  'welten.antwort.arbeitet': '{name} is working …',
  'welten.antwort.nichtGestartet': 'The carrier did not start a turn',
  'welten.antwort.nichtGestartetGrund': 'The carrier did not start a turn: {grund}',
  'welten.antwort.beendet': 'Turn ended without a reply: {grund}',
  'welten.antwort.weg': 'delivered · carrier unreachable',
  'welten.grund.kontingent': 'quota exhausted',
  'welten.grund.anmeldung': 'login missing',
  'welten.grund.recovery_limit': 'retry limit reached',
  'welten.grund.pausiert': 'paused',
  'welten.grund.gestoppt': 'stopped',
  'welten.grund.ungeklaert': 'unresolved run',
  'welten.grund.traeger_aus': 'carrier not running',
  'welten.grund.startfehler': 'start error',
  'welten.grund.chain_limit': 'chain limit reached',
  'welten.grund.cycle': 'wake cycle detected',
  'welten.grund.nicht_erreichbar': 'unreachable',
  'welten.zugart.nachricht': 'Message',
  'welten.zugart.ticket': 'Ticket',
  'welten.zugart.frage': 'Answer to a question',
  'welten.zugart.recovery': 'Recovery',
  'welten.lebenszeichen.titel': 'Turn',
  'welten.lebenszeichen.jetzt': 'Now',
  'welten.lebenszeichen.art': 'Kind',
  'welten.lebenszeichen.grund': 'Reason',
  'welten.lebenszeichen.wecker': 'Next wake-up',
  'welten.lebenszeichen.letzter': 'Last turn',
  'welten.lebenszeichen.letzterText': '{zeit}, {ergebnis}',
  'welten.lebenszeichen.fehler': 'Sign of life not readable: {text}',
  'welten.zeit.datum': '{monat}/{tag} {uhr}',
  'welten.zeit.gerade': 'just now',
  'welten.zeit.minuten': '{n} min ago',
  'welten.zeit.stunden': '{n} h ago',
  'welten.name.du': 'You',
  'welten.name.steuerkanal': 'Control channel',
  'welten.name.alle': 'everyone',
  'welten.team': 'Team {name}',
  'welten.global': 'Global',
  'welten.zaehler.brauchtEins': '{n} needs you',
  'welten.zaehler.brauchenViele': '{n} need you',
  'welten.zaehler.laeuftEins': '{n} running',
  'welten.zaehler.laufenViele': '{n} running',
  'welten.zaehler.ticketEins': '{n} ticket open',
  'welten.zaehler.ticketsViele': '{n} tickets open',
  'welten.messung.zugEins': '{n} turn',
  'welten.messung.zuegeViele': '{n} turns',
  'welten.messung.mittel': 'mean {wert}',
  'welten.messung.letzte': 'last {n}: {wert} ({werte})',
  'welten.meldung.keinKern': 'No connection to the core.',
  'welten.meldung.rueckgabeOhneBemerkung': 'A return needs a note on what is missing.',
  'welten.meldung.ablehnungOhneGrund': 'A rejection needs a reason.',
  'welten.meldung.ausblenden': 'Dismiss',
  'welten.adresse.fehlt': 'In the channel a message needs at least one address.',
  'welten.adresse.unbekannt': '“@{name}” is neither an agent nor a team in {welt}.',
  'welten.adresse.alleAllein': '“@alle” must stand alone.',
  'welten.leiste.vorlagen': 'Templates:',
  'welten.leiste.baum': 'Tree',
  'welten.leiste.liste': 'List',
  'welten.leiste.inkonsistent': 'State read during a write',
  'welten.leiste.teams': 'Teams',
  'welten.leiste.aktiv': '{n} active',
  'welten.leiste.ohneTeam': 'No team',
  'welten.leiste.agenten': 'Agents',
  'welten.kopf.globaleWelt': 'Global world',
  'welten.kopf.inspektor': 'Inspector',
  'welten.kanal.name': 'Channel',
  'welten.kanal.nachrichtEins': '{n} message',
  'welten.kanal.nachrichtenViele': '{n} messages',
  'welten.kanal.unter': 'All agents of {welt} · {n} messages · only addressees are woken',
  'welten.reiter.chat': 'Chat',
  'welten.reiter.tickets': 'Tickets',
  'welten.chat.mitDir': 'With you',
  'welten.chat.direktMit': 'Direct with {namen}',
  'welten.chat.leer': 'No conversation yet',
  'welten.chat.leerAgent': 'You can write to {name}. Replies and reports appear here; questions go through the team lead and the main agent.',
  'welten.chat.leerKanal': 'In the channel all agents of the world write, with addresses.',
  'welten.chat.direktNurLesen': 'Direct chat between agents, read only.',
  'welten.chat.an': 'To',
  'welten.chat.nachrichtAn': 'Message to {name}',
  'welten.chat.nachrichtKanal': 'Message to the channel',
  'welten.chat.senden': 'Send',
  'welten.nachricht.an': 'to {namen}',
  'welten.nachricht.frageAnDich': 'Question for you',
  'welten.nachricht.ergebnisFuerDich': 'Result for you',
  'welten.nachricht.ticket': 'Ticket “{titel}”',
  'welten.nachricht.quittieren': 'Acknowledge',
  'welten.nachricht.quittiert': 'acknowledged',
  'welten.frage.band': 'An open question from {name}: “{text}”',
  'welten.frage.ansehen': 'View',
  'welten.frage.kopf': 'Question from {name} · {stand}',
  'welten.frage.empfohlen': '{option} (recommended)',
  'welten.frage.eigeneAntwort': 'Your own answer',
  'welten.frage.antworten': 'Answer',
  'welten.frage.zuruecknehmen': 'Withdraw …',
  'welten.frage.antwortVon': 'Answer from {name}: {text}',
  'welten.tickets.filterOffen': 'Open',
  'welten.tickets.filterAlle': 'All',
  'welten.tickets.neu': 'New ticket',
  'welten.tickets.neuIn': 'New ticket in {welt}',
  'welten.tickets.titel': 'Title',
  'welten.tickets.ziel': 'Goal',
  'welten.tickets.fertig': 'Done means',
  'welten.tickets.hauptagentEntscheidet': 'Main agent decides',
  'welten.tickets.keine': 'No tickets in this selection.',
  'welten.tickets.alle': '‹ All tickets',
  'welten.ticket.an': 'to {namen}',
  'welten.ticket.von': 'from {name}',
  'welten.ticket.wartetAuf': 'waiting for {liste}',
  'welten.detail.auftrag': 'Order',
  'welten.detail.adressiertAn': 'Addressed to',
  'welten.detail.bearbeiter': 'Assignee',
  'welten.detail.absender': 'Sender',
  'welten.detail.angelegt': 'Created',
  'welten.detail.ergebnis': 'Result',
  'welten.detail.zurueckgegeben': 'Returned',
  'welten.detail.abnahme': 'Approval',
  'welten.detail.wasFehlt': 'What is missing, in one sentence',
  'welten.detail.zurueckgeben': 'Return',
  'welten.detail.zurueckgebenOffen': 'Return …',
  'welten.detail.verlauf': 'History',
  'welten.vorschlag.titel': 'Skill proposal',
  'welten.vorschlag.zeile': '“{skill}” by {agent} for {ziel} · reviewed by {pruefer} · {stand}',
  'welten.vorschlag.zielBibliothek': 'the library',
  'welten.vorschlag.zielWelt': 'the world',
  'welten.vorschlag.begruendung': 'Reason: {text}',
  'welten.vorschlag.version': 'Version {version}, target level so far {basis}',
  'welten.vorschlag.neu': 'new',
  'welten.vorschlag.diffGekuerzt': '[… truncated; complete in diff.txt]',
  'welten.vorschlag.uebernommenVon': 'Accepted by {name}',
  'welten.vorschlag.abgelehntVon': 'Rejected by {name}',
  'welten.vorschlag.grundPlatzhalter': 'Why not, in one sentence',
  'welten.vorschlag.ablehnen': 'Reject',
  'welten.vorschlag.ablehnenOffen': 'Reject …',
  'welten.vorschlag.uebernehmen': 'Accept',
  'welten.vorschlag.pruefen': 'Check: no agent rule loosened, no approval bypassed, no duplicate purpose.',
  'welten.knopf.abbrechen': 'Cancel',
  'welten.knopf.anlegen': 'Create',
  'welten.knopf.pruefen': 'Check',
  'welten.knopf.sichern': 'Save',
  'welten.knopf.verwerfen': 'Discard',
  'welten.knopf.bearbeiten': 'Edit',
  'welten.knopf.bearbeitenOffen': 'Edit …',
  'welten.wort.keiner': 'none',
  'welten.wort.keine': 'none',
  'welten.wort.leer': 'empty',
  'welten.wort.keineEingetragen': 'none set',
  'welten.feld.spezialgebiet': 'Specialty',
  'welten.feld.modell': 'Model',
  'welten.feld.denkstufe': 'Effort',
  'welten.feld.fallback': 'Fallback',
  'welten.feld.fallbackDenkstufe': 'Fallback effort',
  'welten.feld.maschine': 'Machine',
  'welten.feld.werkzeuge': 'Tools',
  'welten.feld.bash': 'Bash patterns',
  'welten.feld.kontextgrenze': 'Context limit',
  'welten.welt.titel': 'World',
  'welten.welt.art': 'Kind',
  'welten.welt.projekt': 'Project',
  'welten.welt.ablage': 'Location',
  'welten.welt.stand': 'State',
  'welten.welt.agentenTeamEins': '{n} in {m} team',
  'welten.welt.agentenTeamsViele': '{n} in {m} teams',
  'welten.welt.ticketsOffen': '{n}, {m} of them open',
  'welten.welt.fragen': 'Questions',
  'welten.welt.fragenOffen': '{n} open of {m}',
  'welten.welt.sofortstopp': 'Emergency stop',
  'welten.welt.sofortstoppText': 'Blocks new starts and ends running turns of the whole world. Tickets in progress are interrupted and never counted as a success.',
  'welten.welt.stoppen': 'Stop the world now …',
  'welten.antrag.titel': 'Requests to the main agent',
  'welten.antrag.zeile': '{agent} for team {team} · {stand} – from {name}: {text}',
  'welten.antrag.offen': 'open',
  'welten.antrag.angelegt': 'created',
  'welten.antrag.abgelehnt': 'rejected',
  'welten.antrag.entscheidet': 'Only {name} can decide (wb-agent antrag-entscheiden).',
  'welten.antrag.derHauptagent': 'the main agent',
  'welten.blatt.profil': 'Profile',
  'welten.blatt.protokoll': 'Log',
  'welten.blatt.gedaechtnis': 'Memory',
  'welten.blatt.skills': 'Skills',
  'welten.protokoll.hinweis': 'The turn log with tool calls comes from the carrier. Until then this shows what {name} entered in tickets and what changed in the profile or memory.',
  'welten.protokoll.ticketEintrag': '{ereignis} “{titel}”',
  'welten.gedaechtnis.bearbeiten': 'Edit memory',
  'welten.gedaechtnis.warnung': '{name} maintains this memory. Your version replaces MEMORY.md; if the file changed in the meantime, nothing is saved and you reload.',
  'welten.profil.betrieb': 'Operation',
  'welten.profil.schalter': 'Switch',
  'welten.profil.stoppen': 'Stop now …',
  'welten.profil.postfach': 'Inbox: {n} of {m} not yet acknowledged',
  'welten.profil.bearbeiten': 'Edit profile',
  'welten.profil.modellBeispiel': 'e.g. sonnet5:high',
  'welten.profil.fallbackLeer': 'empty = none',
  'welten.profil.modellwechsel': 'A model change applies from the next start; a running turn keeps its model.',
  'welten.profil.angelegtVon': 'by {name}',
  'welten.profil.vorlage': 'template {name}',
  'welten.profil.kennung': 'ID',
  'welten.skills.keine': 'No skills yet. Recurring work becomes a script the second time and a skill the third time.',
  'welten.skills.zuklappen': 'Collapse SKILL.md',
  'welten.skills.zeigen': 'Show SKILL.md',
  'welten.skills.vorgeladen': 'preloaded',
  'welten.skills.verdeckt': 'overrides: {liste}',
  'welten.skills.gleicherStand': '(same version)',
  'welten.skills.veraltet': 'skills.json is older than the folder.',
  'welten.skills.gekuerzt': '[… truncated]',
  'welten.skills.fehlt': 'Missing: {liste} (preloaded in the profile, present on no level)',
  'welten.skills.ungueltig': 'Invalid: {liste}',
  'welten.skills.quelleStand': 'From skills.json, as of {zeit}.',
  'welten.skills.quelle': 'From skills.json.',
  'welten.skills.quelleOrdner': 'Resolved from the skill folders without skills.json.',
  'welten.skills.token': 'Tokens per ticket kind',
  'welten.skills.keineMessung': 'No measurement yet. The carrier writes one line per turn to messungen.jsonl.',
  'welten.skills.verlauf': 'Skill history',
  'welten.skills.nochNichts': 'Nothing yet.',
  'welten.anlegen.titel': 'Create agent',
  'welten.anlegen.in': 'Create an agent in {welt}',
  'welten.anlegen.weltSteht': 'The world is {stand}; agents are created only while it runs.',
  'welten.anlegen.unter': 'in {welt} · takes effect with “Create”, nothing is started',
  'welten.anlegen.ausVorlage': 'From the template “{titel}”.',
  'welten.anlegen.beschreibungFehlt': 'First describe in your own words what the agent should do.',
  'welten.anlegen.vorschlagVon': 'Proposal by {kennung}, effort {stufe}{kosten}.',
  'welten.anlegen.vorschlagLaeuft': 'Proposal running …',
  'welten.anlegen.vorschlagErzeugen': 'Generate proposal',
  'welten.anlegen.beschreibung': 'Description',
  'welten.anlegen.beschreibungFuss': 'The description is enough: the model drafts the rest, headless, without tools and without access to the world. What you set yourself stays.',
  'welten.anlegen.beschreibungPlatzhalter': 'What should the agent do? In your own words',
  'welten.anlegen.vorlage': 'Template',
  'welten.anlegen.ohneTeam': 'no team',
  'welten.anlegen.neuesTeamOffen': 'New team …',
  'welten.anlegen.agent': 'Agent',
  'welten.anlegen.name': 'Name',
  'welten.anlegen.stufe': 'Level',
  'welten.anlegen.team': 'Team',
  'welten.anlegen.neuesTeam': 'New team',
  'welten.anlegen.neuesTeamPlatzhalter': 'Name of the new team',
  'welten.anlegen.einSatz': 'in one sentence',
  'welten.anlegen.modellUndMaschine': 'Model and machine',
  'welten.anlegen.modellFuss': 'From wb-state models table, never Fable. Local where it is enough; the Mac only when the work has to be there.',
  'welten.anlegen.werkzeugeUndGrenzen': 'Tools and limits',
  'welten.anlegen.werkzeugeFuss': 'What the house list blocks stays blocked: push, rm -rf, kill, sending mail, permission levels.',
  'welten.anlegen.einsJeZeile': 'one per line',
  'welten.anlegen.kommaGetrennt': 'comma separated',
  'welten.anlegen.kontextPlatzhalter': 'what the agent does not learn',
  'welten.anlegen.figur': 'Figure',
  'welten.anlegen.hauptagentKern': 'The main agent wears the core.',
  'welten.anlegen.farbe': 'Color',
  'welten.anlegen.anweisungen': 'Instructions file (AGENTS.md)',
  'welten.anlegen.anweisungenFuss': 'Leave empty: the file is created from the house template with role, specialty, limits and reporting paths.',
  'welten.anlegen.hausvorlage': 'Generate from the house template',
  'welten.figur.roboter': 'Robot',
  'welten.figur.tier': 'Animal',
  'welten.figur.linse': 'Lens',
  'welten.farbe.entwicklung': 'Development',
  'welten.farbe.recherche': 'Research',
  'welten.farbe.pruefung': 'Review',
  'welten.farbe.gestaltung': 'Design',
  'welten.vorschau.titel': 'Preview',
  'welten.vorschau.ohneNamen': 'unnamed',
  'welten.vorschau.anweisungen': 'Instructions file',
  'welten.vorschau.ausHausvorlage': 'Created from the house template.',
  'welten.dialog.hinweis': 'This goes through the world\'s data library and is then recorded in its files.',
  'welten.dialog.stoppen': 'Stop',
  'welten.dialog.zuruecknehmen': 'Withdraw',
  'welten.leer.laden': 'Loading worlds',
  'welten.leer.ladenText': 'The core reads the worlds through the data library.',
  'welten.leer.keineWelt': 'No world yet',
  'welten.leer.keineWeltText': 'Agents work in worlds: a main agent takes your requests, and teams split the work among themselves. A world belongs to a project folder or is global, with its own channel, tickets and memory.',
  'welten.leer.danach': 'Next: create the main agent, yourself or as a proposal, then build the team and give requests in the chat or as tickets. On the command line the same works with “wb-welt neu <project>/.werkbank/agents”.',
  'welten.neu.knopf': 'New world …',
  'welten.neu.projekt': 'Project world',
  'welten.neu.projektText': 'The agents work in a project folder; the world lives there under .werkbank/agents.',
  'welten.neu.ordner': 'Project folder',
  'welten.neu.ordnerPlatzhalter': 'Absolute path of the project folder',
  'welten.neu.ordnerFehlt': 'Enter the project folder first.',
  'welten.neu.anlegen': 'Create world',
  'welten.neu.global': 'Global world',
  'welten.neu.globalText': 'For work across all projects, without a folder. It lives under {pfad}.',
  'welten.neu.globalAnlegen': 'Create global world',
  'welten.neu.globalDa': 'The global world already exists.',
  'welten.neu.maschine': 'Machine',
  'welten.neu.maschineHier': 'The world is created here and gets its carrier.',
  'welten.neu.maschineMac': 'The world is created on the Mac. No carrier runs here, so agents do not answer here.',
  'welten.neu.maschineOhneTraeger': 'The world is created on {maschine}. No carrier runs there, so agents do not answer there.',
  'welten.neu.maschineFern': 'The world is created on {maschine} under the same path relative to the home folder and gets its carrier there.',
  'welten.neu.maschineWeg': '{maschine} is not reachable ({text}). The world is created once {maschine} answers.',
  'welten.neu.maschineFrage': '{maschine} has not been asked yet; whether it is reachable shows at the latest when creating.',
  'welten.maschine.titel': 'Machine',
  'welten.maschine.diese': '{maschine}, this one',
  'welten.maschine.verbindung': 'Connection',
  'welten.maschine.erreichbar': 'reachable',
  'welten.maschine.wegSeit': 'not reachable since {zeit}: {text}',
  'welten.maschine.traeger': 'Carrier',
  'welten.maschine.traegerLaeuft': 'set up, running',
  'welten.maschine.traegerSchlaeft': 'set up, asleep',
  'welten.maschine.traegerEingerichtet': 'set up',
  'welten.maschine.traegerFehlt': 'not set up',
  'welten.maschine.traegerUnmoeglich': 'not possible on this machine',
  'welten.zugaenge.titel': 'Access',
  'welten.zugaenge.zeile': '{liste} – set up by the human, applies to every agent of the world',
  'welten.maschine.umziehen': 'Move to {maschine} …',
  'welten.maschine.umziehenText': 'The store moves to the machine under the same path; here it stays as …umgezogen-<date>, nothing is deleted. The workbench checks both sides first and asks back.',
  'welten.maschine.hinweisWeg': '{maschine} not reachable since {zeit}. Showing the last state; actions work again once {maschine} answers.',
  'welten.maschine.hinweisMac': 'No carrier runs on the Mac, so agents do not answer here.',
  'welten.maschine.hinweisOhneTraeger': 'No carrier runs on {maschine}, so agents do not answer here.',
  'welten.maschine.hinweisNichtEingerichtet': 'No carrier is set up for this world on {maschine}; agents answer once it is set up.',
  'welten.maschine.fussErreichbar': '{maschine} reachable, {n} carriers',
  'welten.maschine.fussWeg': '{maschine} not reachable since {zeit}',
  'welten.dialog.umziehen': 'Move',
  'welten.anlegen.hauptagent': 'Create main agent',
  'welten.anlegen.hauptagentOffen': 'Create main agent …',
  'welten.anlegen.vorschlagen': 'Have it proposed …',
  'welten.anlegen.grundFehler': 'The world is not fully readable; agents are created once it is again.',
  'welten.anlegen.vorschlagHinweis': 'Describe in one or two sentences what the new agent should be responsible for in {welt}; “Generate proposal” fills in the rest.',
  'welten.anlegen.vorschlagHinweisHaupt': 'Describe in one or two sentences what {welt} is for and what the main agent should be responsible for; “Generate proposal” fills in the rest.',
  'welten.anlegen.gespraech': 'Conversation',
  'welten.anlegen.formular': 'Form',
  'welten.anlegen.ansichtTipp': 'Work out the draft in a conversation with a model or set it yourself in the form; both show the same draft.',
  'welten.anlegen.gespraechTitel': 'Draft in a conversation',
  'welten.anlegen.gespraechEinladung': 'Describe in your own words what the new agent should do in {welt}: purpose, tone, tasks, limits.',
  'welten.anlegen.gespraechEinladungHaupt': 'Describe in your own words what {welt} is for and what the main agent should be responsible for: purpose, tone, tasks, limits.',
  'welten.anlegen.gespraechErklaerung': 'The model asks follow-up questions, proposes values and enters them in the draft; the preview on the right shows the current state. You can change everything in the form at any time, and what you set there stays. The model runs headless, without tools and without access to the world.',
  'welten.anlegen.gespraechPlatzhalter': 'What should the agent do?',
  'welten.anlegen.gespraechAntwortPlatzhalter': 'Reply to the model',
  'welten.anlegen.gespraechModell': 'Model for the conversation',
  'welten.anlegen.gespraechLaeuft': '{modell} is answering …',
  'welten.anlegen.gespraechFertig': 'Complete from the model’s point of view. Check, then create.',
  'welten.anlegen.sendenTipp': 'Send (⌘↩)',
  'welten.anlegen.nachrichtFehlt': 'First write what the agent should do.',
  'welten.anlegen.antwortVon': 'Answer by {kennung}, effort {stufe}{kosten}.',
  'welten.anlegen.zuletztGesetzt': 'Last set: {felder}',
  'welten.anlegen.gesetzt': 'Set: {felder}',
  'welten.anlegen.imFormular': 'View in the form',
  'welten.anlegen.du': 'You',
  'welten.anlegen.modell': 'Model',
  'welten.entwurfsfeld.id': 'Name',
  'welten.entwurfsfeld.stage': 'Level',
  'welten.entwurfsfeld.team': 'Team',
  'welten.entwurfsfeld.specialty': 'Specialty',
  'welten.entwurfsfeld.model': 'Model',
  'welten.entwurfsfeld.effort': 'Effort',
  'welten.entwurfsfeld.fallback_model': 'Fallback',
  'welten.entwurfsfeld.fallback_effort': 'Fallback effort',
  'welten.entwurfsfeld.machine': 'Machine',
  'welten.entwurfsfeld.tools': 'Tools',
  'welten.entwurfsfeld.bash': 'Bash patterns',
  'welten.entwurfsfeld.skills': 'Skills',
  'welten.entwurfsfeld.context_limit': 'Context limit',
  'welten.entwurfsfeld.figure': 'Figure',
  'welten.entwurfsfeld.instructions': 'Instructions file',
  'welten.entwurfsfeld.template': 'Template',
  'welten.einladung.titel': 'This world has no main agent yet.',
  'welten.einladung.text': 'Create it or have it proposed. It takes your requests, hands them to the teams as tickets and asks you only when there is no other way.',
  'welten.leiste.hauptagent': 'Main agent',
  'welten.leiste.keinHauptagent': 'No main agent yet',
};

/** Die Tabellen je Sprache. */
const TABELLEN: Record<Sprache, Record<string, string>> = { de: DE, en: EN };

let aktuelleSprache: Sprache = 'en';

/** Die Sprache umstellen. Ein unbekannter oder fehlender Wert faellt auf Englisch zurueck. */
export function setzeSprache(s: string | undefined): void {
  aktuelleSprache = s === 'de' ? 'de' : 'en';
}

/** Welche Sprache gerade gilt. */
export function sprache(): Sprache {
  return aktuelleSprache;
}

/**
 * DIE EINE ABFRAGE. Ein fehlender Schluessel wird SICHTBAR gemeldet und nicht
 * durch einen leeren Text ersetzt: eine Luecke, die man sieht, wird behoben.
 */
export function t(schluessel: string, werte?: Record<string, string | number>): string {
  const tabelle = TABELLEN[aktuelleSprache] ?? DE;
  const roh = tabelle[schluessel] ?? DE[schluessel];
  if (roh === undefined) return `[fehlender Text: ${schluessel}]`;
  if (!werte) return roh;
  return roh.replace(/\{([A-Za-z][A-Za-z0-9]*)\}/g, (ganz, name: string) => {
    const w = werte[name];
    return w === undefined ? ganz : String(w);
  });
}

/** Nur fuer Tests und fuer die Uebersetzung: alle Schluessel der Referenztabelle (Deutsch). */
export function alleSchluessel(): string[] {
  return Object.keys(DE).sort();
}
